-- Dungeon Route Guide - dungeon data (generated).
-- Dungeon metadata and localized guide text.
-- Bundled native minimap geometry and markers are loaded by MinimapData.lua.
local _, ns = ...

ns.Dungeons = {
  {
    key = "rfc", slug = "ragefire-chasm", levels = "13-18",
    name = { ko = "성난불길 협곡", en = "Ragefire Chasm" },
    instanceIDs = { 389 }, nameMatch = { "성난불길", "Ragefire" },
    entrance = { map = 1454, x = 53.0, y = 48.9, zone = { ko = "오그리마 어둠의 틈 안쪽 동굴", en = "Inside the Cleft of Shadow in Orgrimmar" } },
    steps = {
      { id = "s1", n = "1", kind = "fork", unconfirmed = true, name = { ko = "갈림길", en = "Junction" }, tip = { ko = "입구 복도 끝 갈림길입니다. 서쪽으로 가서 오글플린트부터 잡고, 나중에 이 자리로 돌아옵니다.", en = "Junction at the end of the entrance corridor. Go west for Oggleflint first; you return here later." } },
      { id = "s2", n = "2", kind = "boss", npc = { 11517 }, model = 11611, name = { ko = "오글플린트", en = "Oggleflint" }, loot = { 272996, 272998, 272999 }, tip = { ko = "회전베기를 씁니다. 탱커 말고는 정면을 피하세요.", en = "Cleaves, so only the tank stands in front." } },
      { id = "s3", n = "3", kind = "object", name = { ko = "마우리 그림토템의 시체", en = "Muurin Grimtotem's corpse" }, quest = true, quests = { 5722 }, tip = { ko = "용암 옆 오르막 끝 막다른 굴에 있는 시체입니다. '잃어버린 가방 찾기'의 가방을 여기서 줍습니다.", en = "Corpse in a dead-end nook up the lava path. Loot the satchel for Searching for the Lost Satchel." } },
      { id = "s4", n = "4", kind = "fork", unconfirmed = true, name = { ko = "갈림길", en = "Junction" }, tip = { ko = "왔던 길로 다시 갈림길에 돌아와, 이번엔 남쪽 길로 올라갑니다.", en = "Back at the junction, take the southern path up this time." } },
      { id = "s5", n = "5", kind = "boss", npc = { 11520 }, model = 7970, name = { ko = "욕망의 타라가만", en = "Taragaman the Hungerer" }, quest = true, loot = { 14149, 14148, 14145 }, quests = { 5761 }, tip = { ko = "불꽃 회오리로 주변 전체를 태우고 올려치기로 탱커를 띄웁니다. 근접은 체력을 넉넉히. 심장은 '야수 처단' 퀘스트 아이템.", en = "Fire Nova hits everyone close and Uppercut launches the tank. Melee keep health up. His heart is for Slaying the Beast." } },
      { id = "s6", n = "6", kind = "boss", npc = { 11519 }, model = 2007, name = { ko = "바잘란", en = "Bazzalan" }, quest = true, loot = { 273003, 273007, 273005 }, quests = { 5728 }, tip = { ko = "타라가만 다음, 서쪽 가장자리 길로 돌아 올라가면 있습니다. 사악한 일격과 독. 독을 해제하세요.", en = "After Taragaman, loop up the western edge. Sinister Strike and poison; cure it." } },
      { id = "s7", n = "7", kind = "boss", npc = { 11518 }, model = 11429, name = { ko = "기원사 제로쉬", en = "Jergosh the Invoker" }, quest = true, loot = { 14150, 14147, 14151 }, quests = { 5725, 5728 }, tip = { ko = "바잘란 자리에서 절벽 아래로 뛰어내리면 바로 앞입니다. 제물과 무력화 저주. 저주 해제, 시전 차단.", en = "Jump down the cliff from Bazzalan's ledge and you land on him. Immolate and Curse of Weakness: decurse and interrupt." } },
    },
    quests = {
      { id = 5723, faction = "Horde", level = 15, name = { ko = "성난불길 협곡의 트로그", en = "Testing an Enemy's Strength" }, giver = { ko = "오그리마에 있는 성난불길 협곡을 찾아 성난불길 트로그 8마리와 성난불길일족 주술사 8마리를 처치하고 썬더 블러프에 있는 라하우로에게 돌아가야 합니다.", en = "Search Orgrimmar for Ragefire Chasm, then kill 8 Ragefire Troggs and 8 Ragefire Shaman before returning to Rahauro in Thunder Bluff." } },
      { id = 5728, faction = "Horde", level = 16, name = { ko = "내부의 배신자", en = "Hidden Enemies" }, giver = { ko = "바잘란과 기원사 제로쉬를 제거한 다음 오그리마에 있는 스랄에게 돌아가야 합니다.", en = "Kill Bazzalan and Jergosh the Invoker before returning to Thrall in Orgrimmar." } },
      { id = 5761, faction = "Horde", level = 16, name = { ko = "야수 처단", en = "Slaying the Beast" }, giver = { ko = "성난불길 협곡으로 가서 욕망의 타라가만을 제거한 다음 그의 심장을 오그리마에 있는 네루 파이어블레이드에게 가져가야 합니다.", en = "Enter Ragefire Chasm and slay Taragaman the Hungerer, then bring his heart back to Neeru Fireblade in Orgrimmar." } },
      { id = 5722, faction = "Horde", level = 16, name = { ko = "잃어버린 가방 찾기", en = "Searching for the Lost Satchel" }, giver = { ko = "성난불길 협곡에서 마우리 그림토템의 시체를 찾아 도움이 될 만한 것들을 찾아야 합니다.", en = "Search Ragefire Chasm for Maur Grimtotem's corpse and search it for any items of interest." } },
      { id = 5725, faction = "Horde", level = 16, name = { ko = "파괴해야 할 힘", en = "The Power to Destroy..." }, giver = { ko = "언더시티에 있는 바리마트라스에게 어둠의 주문서와 황천의 마법서를 가져가야 합니다.", en = "Bring the books Spells of Shadow and Incantations from the Nether to Varimathras in Undercity." } },
    },
    notes = { { ko = "화염 피해가 계속 들어오니 물약·붕대를 넉넉히.", en = "Constant fire damage: bring potions and bandages." }, { ko = "저주·독 해제가 있으면 두 우두머리가 쉬워집니다.", en = "Decurse and poison cures make two bosses easy." } },
  },
  {
    key = "thanes", slug = "hall-of-thanes", levels = "13-18",
    name = { ko = "영주의 전당", en = "The Hall of Thanes" },
    instanceIDs = { 3065 }, nameMatch = { "영주의 전당", "Hall of Thanes" },
    entrance = { map = 1455, x = 43.6, y = 51.7, zone = { ko = "아이언포지 왕좌의 방(마그니 왕)에서 왼쪽 길로 내려가 옛 아이언포지로", en = "Take the left path from King Magni's throne room down into Old Ironforge" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", name = { ko = "팔드림 앤빌마", en = "Faldrim Anvilmar" }, loot = { 270227, 271096, 271097 }, tip = { ko = "입구 다음 큰 방(앤빌마의 휴식처). 망령이 가득하니 앞만 비우든 방을 다 치우든 편한 대로. 정신 분열은 차단, 탱커 공속을 늦추는 저주를 겁니다.", en = "Big hall past the entrance, full of ghosts; clear in front or the whole room. Interrupt Mind Blast; curse slows the tank's attacks." } },
      { id = "s2", n = "2", kind = "boss", name = { ko = "마그마투스", en = "Magmatus" }, loot = { 270230, 270231, 271095 }, tip = { ko = "휴식처에서 동쪽 깊은 곳. 소환사와 함께 오니 소환사부터. 연소(차단 불가, 12초 화염)와 즉시 화염 폭발. 비근접은 떨어져 서세요.", en = "Deep to the east. Comes with a Summoner: kill it first. Combust (12s, can't kick) and instant Fire Nova; non-melee stand back." } },
      { id = "s3", n = "3", kind = "boss", name = { ko = "약탈골렘", en = "Plunder" }, loot = { 270228, 271098, 270229 }, tip = { ko = "마그마투스 방에서 서쪽 끝 큰 본당. 복도를 순찰하니 구석으로 끌어오세요. 넉백이 있으니 벽을 등지고.", en = "West to the great hall of thrones. Patrols his corridor; pull into a cleared corner. Knock Away, so back to a wall." } },
      { id = "s4", n = "4", kind = "boss", name = { ko = "드루겐 더지해머", en = "Durgen Dirgehammer" }, loot = { 270256, 270260, 270261 }, tip = { ko = "약탈골렘 다음 북쪽 '왕가의 성물 보관소'. 옆 약탈자와 작은 돌 골렘부터. 출혈과 8초 광역 공포가 있으니 방을 미리 비우세요.", en = "North to the Reliquary of Kings. Clear looters and the small golems first. Rend and an 8s AoE fear; empty the room beforehand." } },
    },
    quests = {
      { id = 96394, faction = "Alliance", level = 15, name = { ko = "안식 없는 죽음", en = "The Restless Dead" }, giver = { ko = "분노한 원혼 15명과 고통받는 영혼 10명을 처치하고 앤빌마의 영혼을 안식에 들게 해야 합니다.", en = "Kill 15 Enraged Apparitions, 10 Tormented Souls and put the spirit of Anvilmar to rest." } },
      { id = 98423, faction = "Alliance", level = 16, name = { ko = "이해의 조약", en = "The Treaty of Understanding" }, giver = { ko = "영주의 전당 마지막 방의 금고 문 뒤에 있는 돌판을 아이언포지의 마그니 브론즈비어드에게 가져가야 합니다.", en = "Bring the stone tablet from behind the vault door in the Hall of Thanes' last room to Magni Bronzebeard in Ironforge." } },
      { id = 96393, faction = "Alliance", level = 16, name = { ko = "구 아이언포지 침입", en = "Old Ironforge Incursion" }, giver = { ko = "구 아이언포지 지하에 있는 영주의 전당에 진입해 드루겐 더지해머의 머리카락을 확보해야 합니다.", en = "Enter the Hall of Thanes beneath Old Ironforge and claim the Head of Durgen Dirgehammer." } },
      { id = 96403, level = 15, name = { ko = "중요한 가보", en = "Important Heirlooms" }, giver = { ko = "영주의 전당에서 드워프 가보 8개를 입수해야 합니다.", en = "Collect 8 Dwarven Heirlooms from the Hall of Thanes." } },
      { id = 96395, level = 15, name = { ko = "해묵은 원한", en = "An Ancient Grudge" }, giver = { ko = "영주의 전당에서 팔드림 앤빌마의 영혼에게 안식을 선사해야 합니다.", en = "Put the spirit of Faldrim Anvilmar to rest in the Hall of Thanes." } },
    },
    notes = { { ko = "내려가는 길 아래가 용암입니다. 길에서 벗어나지 마세요.", en = "Lava below the descending path; stay on it." }, { ko = "마그마투스 구간은 화염 저항 물약이 도움이 됩니다.", en = "Fire resistance potions help for Magmatus." } },
  },
  {
    key = "wc", slug = "wailing-caverns", levels = "15-24",
    name = { ko = "통곡의 동굴", en = "Wailing Caverns" },
    instanceIDs = { 43 }, nameMatch = { "통곡의 동굴", "Wailing Caverns" },
    entrance = { map = 1413, x = 47.7, y = 35.0, zone = { ko = "불모의 땅 오아시스 남쪽 협곡의 동굴", en = "Cave in the ravine south of the oasis, The Barrens" } },
    steps = {
      { id = "s1", n = "1", kind = "rare", optional = true, outside = { ko = "던전 밖 · 불모의 땅 46.1, 35.8", en = "Outside the dungeon · The Barrens 46.1, 35.8" }, npc = { 3655 }, model = 7221, name = { ko = "광기의 매글리시", en = "Mad Magglish" }, quests = { 959 }, tip = { ko = "던전 입구 앞 바깥 동굴(날팍 근처)에 숨은 정예입니다. '99년 묵은 와인'의 포트 와인을 떨구니 들어가기 전에 잡으세요.", en = "Elite hiding in the outer cave by Nalpak. Drops the port for Trouble at the Docks; kill him before zoning in." } },
      { id = "s2", n = "2", kind = "boss", npc = { 3671 }, model = 4313, name = { ko = "여군주 아나콘드라", en = "Lady Anacondra" }, quest = true, loot = { 273088, 10412, 5404, 6446, 273098 }, quests = { 914 }, tip = { ko = "번개 화살·수면·치유의 손길, 가시 오라. 치유는 꼭 끊으세요. 송곳니의 군주 넷 중 하나.", en = "Lightning Bolt, Sleep, Healing Touch and Thorns. Always kick the heal. One of the four Fanglords." } },
      { id = "s3", n = "3", kind = "boss", npc = { 3669 }, model = 4213, name = { ko = "군주 코브란", en = "Lord Cobrahn" }, quest = true, loot = { 6460, 10410, 6465 }, quests = { 914 }, tip = { ko = "치유를 쓰다가 뱀으로 변해 독을 겁니다. 치유 차단, 독 해제. 송곳니의 군주.", en = "Heals, then turns into a serpent that poisons. Interrupt heals, cure poison. A Fanglord." } },
      { id = "s4", n = "4", kind = "boss", optional = true, npc = { 3653 }, model = 5126, name = { ko = "크레쉬", en = "Kresh" }, loot = { 273084, 13245, 6447 }, tip = { ko = "기술 없는 거북. 물길을 따라 천천히 돌아다니니 끌어와서 잡으면 됩니다.", en = "Harmless turtle wandering the water. Just pull it." } },
      { id = "s5", n = "5", kind = "boss", npc = { 3670 }, model = 4214, name = { ko = "군주 피타스", en = "Lord Pythas" }, quest = true, loot = { 273089, 6472, 6473 }, quests = { 914 }, tip = { ko = "번개 화살·수면·천둥벼락·치유. 치유를 끊으세요. 송곳니의 군주.", en = "Lightning Bolt, Sleep, Thunderclap and heals. Kick the heals. A Fanglord." } },
      { id = "s6", n = "6", kind = "boss", optional = true, npc = { 3674 }, model = 4203, name = { ko = "스컴", en = "Skum" }, loot = { 273137, 6449, 6448 }, tip = { ko = "사슬 번개를 쓰고 체력이 낮으면 도망칩니다. 달아나지 못하게 붙잡으세요.", en = "Chained Bolt; runs at low health, so stop him fleeing." } },
      { id = "s7", n = "7", kind = "rare", optional = true, npc = { 5912 }, model = 1267, name = { ko = "돌연변이 요정용", en = "Deviate Faerie Dragon" }, loot = { 5243, 6632 }, tip = { ko = "동쪽 굴을 떠도는 희귀 몹. 보이면 잡고 없으면 지나가세요.", en = "Rare wandering the eastern caves. Kill if up, else move on." } },
      { id = "s8", n = "8", kind = "boss", npc = { 3673 }, model = 4215, name = { ko = "군주 서펜티스", en = "Lord Serpentis" }, quest = true, loot = { 6469, 5970, 10411, 6459, 273087 }, quests = { 914 }, tip = { ko = "번개 화살·수면·치유. 치유 차단. 송곳니의 군주 마지막.", en = "Lightning Bolt, Sleep, heals. Kick heals. The last Fanglord." } },
      { id = "s9", n = "9", kind = "boss", npc = { 5775 }, model = 4256, name = { ko = "영생의 베르단", en = "Verdan the Everliving" }, loot = { 6630, 6631, 6629 }, tip = { ko = "휘감는 덩굴로 주변을 넘어뜨립니다. 힐러는 거리를 두세요.", en = "Grasping Vines knocks down everyone close; healers stay back." } },
      { id = "s10", n = "10", kind = "task", name = { ko = "나랄렉스의 제자 호위", en = "Escort Naralex's Disciple" }, quest = true, quests = { 1491 }, tip = { ko = "송곳니의 군주 넷이 죽으면 제자가 의식을 하러 움직입니다. 따라가며 몰려오는 몹을 잡고 지켜 주세요.", en = "With the four Fanglords dead the Disciple starts his ritual walk. Follow and protect him from the waves." } },
      { id = "s11", n = "11", kind = "boss", npc = { 3654 }, model = 4088, name = { ko = "걸신들린 무타누스", en = "Mutanus the Devourer" }, quest = true, loot = { 6461, 6627, 6463, 10441 }, quests = { 6981 }, tip = { ko = "호위가 끝나면 나타납니다. 공포·천둥균열·수면(나랄렉스의 악몽). '빛나는 조각'이 나올 수 있어요.", en = "Appears after the escort. Terrify, Thundercrack and a sleep. May drop The Glowing Shard." } },
    },
    quests = {
      { id = 962, faction = "Horde", level = 18, name = { ko = "불뱀꽃", en = "Serpentbloom" }, giver = { ko = "썬더 블러프에 있는 연금술사 자마가 불뱀꽃 10개를 모아 달라고 부탁했습니다.", en = "Apothecary Zamah in Thunder Bluff wants you to collect 10 Serpentbloom." } },
      { id = 914, faction = "Horde", level = 22, name = { ko = "송곳니의 드루이드 우두머리", en = "Leaders of the Fang" }, giver = { ko = "코브란, 아나콘드라, 피타스, 서펜티스의 보석을 모아 썬더 블러프에 있는 나라 와일드메인에게 돌아가야 합니다.", en = "Bring the Gems of Cobrahn, Anacondra, Pythas and Serpentis to Nara Wildmane in Thunder Bluff." } },
      { id = 1486, level = 17, name = { ko = "돌연변이 통가죽", en = "Deviate Hides" }, giver = { ko = "통곡의 동굴에 있는 날팍이 돌연변이 통가죽 20개를 가져다 달라고 부탁했습니다.", en = "Nalpak in the Wailing Caverns wants 20 Deviate Hides." } },
      { id = 959, level = 18, name = { ko = "99년 묵은 와인", en = "Trouble at the Docks" }, giver = { ko = "톱니항에 있는 기중기 기사 비글퍼즈가 통곡의 동굴에 숨어 있는 광기의 매글리시에게서 99년 숙성된 포트 와인을 되찾아 달라고 부탁했습니다.", en = "Crane Operator Bigglefuzz in Ratchet wants you to retrieve the bottle of 99-Year-Old Port from Mad Magglish who is hiding in the Wailing Caverns." } },
      { id = 1491, level = 18, name = { ko = "영리해지는 음료", en = "Smart Drinks" }, giver = { ko = "톱니항에 있는 메보크 미지릭스에게 통곡의 정수 6병을 가져가야 합니다.", en = "Bring 6 portions of Wailing Essence to Mebok Mizzyrix in Ratchet." } },
      { id = 1487, level = 21, name = { ko = "돌연변이 짐승 섬멸", en = "Deviate Eradication" }, giver = { ko = "통곡의 동굴에 있는 에브루가 돌연변이 약탈자랩터 7마리, 돌연변이 독사 7마리, 돌연변이 늪괴물 7마리, 돌연변이 송곳니천둥매 7마리를 처치해 달라고 부탁했습니다.", en = "Ebru in the Wailing Caverns wants you to kill 7 Deviate Ravagers, 7 Deviate Vipers, 7 Deviate Shamblers and 7 Deviate Dreadfangs." } },
      { id = 6981, level = 26, name = { ko = "빛나는 조각", en = "The Glowing Shard" }, giver = { ko = "톱니항으로 가서 빛나는 조각에 대해 자세히 얘기해 줄 수 있는 이를 찾으십시오. 그에게 지시를 받아, 빛나는 조각을 전달해야 합니다.", en = "Travel to Ratchet to find someone that can tell you more about the glowing shard. Then, deliver the shard as you are directed." } },
    },
    trash = { 10413 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 10413 }, from = { [10413] = { { n = { ko = "송곳니의 드루이드", en = "Druid of the Fang" }, r = 2.34 } } } },
    },
    notes = { { ko = "송곳니의 드루이드는 치유의 손길을 씁니다. 차단을 나눠 맡으세요.", en = "Fanglords heal: assign interrupts." }, { ko = "층이 겹친 동굴입니다. 함부로 뛰어내리면 돌아오기 어렵습니다.", en = "Layered caves: jumping down can split the group." }, { ko = "랩터는 체력이 줄면 주변을 부릅니다. 주변을 비우고 잡으세요.", en = "Raptors call help at low health; clear around first." } },
  },
  {
    key = "dm", slug = "deadmines", levels = "17-26",
    name = { ko = "죽음의 폐광", en = "The Deadmines" },
    instanceIDs = { 36 }, nameMatch = { "죽음의 폐광", "Deadmines" },
    entrance = { map = 1436, x = 38.2, y = 77.5, zone = { ko = "서부 몰락지대 달빛시내 마을 광산 안쪽", en = "Inside the mine at Moonbrook, Westfall" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 644 }, model = 14403, name = { ko = "라크조르", en = "Rhahk'Zor" }, loot = { 273289, 872, 5187 }, tip = { ko = "격돌로 탱커를 기절시킵니다. 기절한 동안 힐러가 체력을 채워 주세요.", en = "Slam stuns the tank; healer tops them up meanwhile." } },
      { id = "s2", n = "2", kind = "rare", optional = true, npc = { 3586 }, model = 556, name = { ko = "광부 존슨", en = "Miner Johnson" }, loot = { 5443, 5444 }, tip = { ko = "옆길 작은 방의 희귀 정예. 건너뛰어도 됩니다.", en = "Rare elite in a side room. Skippable." } },
      { id = "s3", n = "3", kind = "boss", npc = { 643, 642 }, model = 7125, name = { ko = "스니드", en = "Sneed" }, quest = true, loot = { 273293, 5194, 5195, 273092, 1937, 2169, 285292 }, quests = { 2040 }, tip = { ko = "스니드의 벌목기를 먼저 부수면 스니드가 튀어나옵니다. 무장 해제를 씁니다.", en = "Break Sneed's Shredder and he jumps out. He disarms." } },
      { id = "s4", n = "4", kind = "boss", npc = { 1763 }, model = 7124, name = { ko = "길니드", en = "Gilnid" }, quest = true, loot = { 273297, 1156, 5199, 273086 }, quests = { 2040 }, tip = { ko = "용해된 금속을 뿌리고 제련공들이 합류합니다. 쫄부터 정리하세요.", en = "Molten Metal; smelters join the fight. Clear adds first." } },
      { id = "s5", n = "5", kind = "object", name = { ko = "데피아즈단 화약", en = "Defias Gunpowder" }, quest = true, quests = { 92753 }, tip = { ko = "제련소 옆 화약 더미. '죽음의 폐광 파괴 작전'의 폭발물은 이 근처 숨은 가열로에 설치합니다.", en = "Gunpowder by the foundry. Plant the explosives for Destruction in Deadmines at the hidden forge here." } },
      { id = "s6", n = "6", kind = "boss", npc = { 646 }, model = 2026, name = { ko = "미스터 스마이트", en = "Mr. Smite" }, loot = { 284715, 7230, 5192, 5196 }, tip = { ko = "여기부터 배입니다. 체력이 줄면 발구르기로 파티를 기절시키고 상자에서 무기를 바꿉니다. 기절이 풀리면 다시 모이세요.", en = "The ship starts here. At health thresholds he stuns everyone and swaps weapons at his chest; regroup after." } },
      { id = "s7", n = "7", kind = "boss", npc = { 645 }, model = 1305, name = { ko = "쿠키", en = "Cookie" }, loot = { 273298, 5198, 5197, 273102 }, tip = { ko = "갑판 아래 주방. 요리로 자신을 치유하고 산성 물질을 끼얹습니다. 요리를 끊으세요.", en = "Galley below deck. Heals himself by cooking and splashes acid; interrupt the cooking." } },
      { id = "s8", n = "8", kind = "boss", npc = { 647 }, model = 7113, name = { ko = "선장 그린스킨", en = "Captain Greenskin" }, loot = { 5201, 10403, 5200 }, tip = { ko = "독 묻은 작살과 회전베기. 독을 해제하고 탱커 뒤에 서세요.", en = "Poisoned Harpoon and Cleave. Cure poison, stand behind." } },
      { id = "s9", n = "9", kind = "boss", npc = { 639 }, model = 2029, name = { ko = "에드윈 밴클리프", en = "Edwin VanCleef" }, quest = true, loot = { 5193, 5202, 10399, 5191 }, quests = { 166, 373 }, tip = { ko = "배 뒤쪽 윗갑판의 마지막 우두머리. 쌍수 난타, 체력이 줄면 호위병을 부릅니다. 쫄은 묶거나 먼저 잡으세요. '부치지 않은 편지'를 챙기세요.", en = "Final boss on the upper deck aft. Thrash, then calls guards as he weakens; control or kill them. Grab The Unsent Letter." } },
    },
    quests = {
      { id = 214, faction = "Alliance", level = 17, name = { ko = "붉은 비단 복면", en = "Red Silk Bandanas" }, giver = { ko = "감시의 언덕 탑의 정찰병 리엘이 붉은 비단 복면 10개를 가져다 달라고 부탁했습니다.", en = "Scout Riell at the Sentinel Hill Tower wants you to bring her 10 Red Silk Bandanas." } },
      { id = 168, faction = "Alliance", level = 18, name = { ko = "기억을 더듬어...", en = "Collecting Memories" }, giver = { ko = "스톰윈드에 있는 빌더 시슬네틀에게 광부 조합의 명함 4장을 가져가야 합니다.", en = "Retrieve 4 Miners' Union Cards and return them to Wilder Thistlenettle in Stormwind." } },
      { id = 92753, faction = "Alliance", level = 18, name = { ko = "죽음의 폐광 파괴 작전", en = "Destruction in Deadmines" }, giver = { ko = "죽음의 폐광에서 숨겨진 가열로를 찾아 주변에 강력 파괴 폭발물을 설치해야 합니다. 그런 다음 죽음의 폐광 출구에서 알바 페어문을 만나야 합니다.", en = "Find the forge hidden in the Deadmines, and plant the Extra-Destructive Explosives nearby. Then, meet up with Alba Fairmoon at the Deadmines exit." } },
      { id = 2040, faction = "Alliance", level = 20, name = { ko = "지하 공격", en = "Underground Assault" }, giver = { ko = "죽음의 폐광에서 노암 톱니구동장치를 찾아 스톰윈드에 있는 쇼니에게 가져가야 합니다.", en = "Retrieve the Gnoam Sprecklesprocket from the Deadmines and return it to Shoni the Shilent in Stormwind." } },
      { id = 167, faction = "Alliance", level = 20, name = { ko = "형제여...", en = "Oh Brother..." }, giver = { ko = "스톰윈드에 있는 빌더 시슬네틀에게 시슬네틀의 배지를 가져가야 합니다.", en = "Bring Foreman Thistlenettle's Explorers' League Badge to Wilder Thistlenettle in Stormwind." } },
      { id = 166, faction = "Alliance", level = 22, name = { ko = "데피아즈단", en = "The Defias Brotherhood" }, giver = { ko = "에드윈 밴클리프를 처치하고 그 증거로 그의 가면을 그라이언 스타우트맨틀에게 가져가야 합니다.", en = "Kill Edwin VanCleef and bring his head to Gryan Stoutmantle." } },
      { id = 373, faction = "Alliance", level = 22, name = { ko = "부치지 않은 편지", en = "The Unsent Letter" }, giver = { ko = "스톰윈드에 있는 도시 건축가 바로스 알렉스턴에게 편지를 전달해야 합니다.", en = "Deliver the Letter to the City Architect to Baros Alexston in Stormwind." } },
    },
    trash = { 1934, 10402, 1943, 1951, 10400, 10401, 1929, 1930, 1936, 1944, 1945, 1925 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 1934, 10402, 1943, 1951, 10400, 10401, 1929, 1930, 1936, 1944, 1945, 1925 }, from = { [1934] = { { n = { ko = "데피아즈단 검은자객", en = "Defias Blackguard" }, r = 6 } }, [10402] = { { n = { ko = "데피아즈단 갱부", en = "Defias Strip Miner" }, r = 3 } }, [1943] = { { n = { ko = "고블린 조선공", en = "Goblin Shipbuilder" }, r = 6 } }, [1951] = { { n = { ko = "데피아즈단 얼음마법사", en = "Defias Squallshaper" }, r = 6 }, { n = { ko = "데피아즈단 해적", en = "Defias Pirate" }, r = 6 } }, [10400] = { { n = { ko = "데피아즈단 작업반장", en = "Defias Taskmaster" }, r = 3 }, { n = { ko = "데피아즈단 감독관", en = "Defias Overseer" }, r = 3 } }, [10401] = { { n = { ko = "데피아즈단 작업반장", en = "Defias Taskmaster" }, r = 3 }, { n = { ko = "데피아즈단 감독관", en = "Defias Overseer" }, r = 3 } }, [1929] = { { n = { ko = "데피아즈단 마술사", en = "Defias Wizard" }, r = 6 }, { n = { ko = "데피아즈단 기원사", en = "Defias Evoker" }, r = 6 } }, [1930] = { { n = { ko = "데피아즈단 광부", en = "Defias Miner" }, r = 3 } }, [1936] = { { n = { ko = "고블린 기술자", en = "Goblin Engineer" }, r = 6 } }, [1944] = { { n = { ko = "고블린 땜장이", en = "Goblin Craftsman" }, r = 5 } }, [1945] = { { n = { ko = "고블린 목공", en = "Goblin Woodcarver" }, r = 7 } }, [1925] = { { n = { ko = "데피아즈단 보초", en = "Defias Watchman" }, r = 7 } } } },
    },
    notes = { { ko = "달빛시내 마을 가는 길에 데피아즈단 정예가 돌아다닙니다. 입구 앞에서 모이세요.", en = "Defias elites roam Moonbrook; meet at the entrance." }, { ko = "밴클리프가 떨구는 '부치지 않은 편지'를 챙기세요.", en = "Loot The Unsent Letter from VanCleef." } },
  },
  {
    key = "rol", slug = "ruins-of-lordaeron", levels = "15-20",
    name = { ko = "로데론의 폐허", en = "Ruins of Lordaeron" },
    instanceIDs = { 2999 }, nameMatch = { "로데론의 폐허", "Ruins of Lordaeron" },
    steps = {
      { id = "s1", n = "1", kind = "npc", optional = true, name = { ko = "트루먼 대위", en = "Captain Truman" }, quest = true, quests = { 95250 }, tip = { ko = "입구를 나와 바로 왼쪽(북쪽) 벽돌 길의 NPC. 얼라이언스 '흉측한 괴물들'을 주고받습니다(남작의 머리).", en = "Just left (north) of the entrance on the brick path. Alliance quest Abominable Creatures (the Baron's head)." } },
      { id = "s2", n = "2", kind = "boss", name = { ko = "쇠퇴송곳니", en = "Witherfang" }, quest = true, loot = { 271203, 271201, 271202 }, quests = { 95216 }, tip = { ko = "동쪽 거미 구역 넓은 방. 쫄 셋을 달고 긴 복도를 순찰하니, 자리를 비운 사이 남은 무리를 치우세요. 탱커에게 흡혈 독. 호드 '새로운 역병'의 균주.", en = "Big room in the east spider area. Patrols the hallway with three adds; clear while she's away. Leech Poison on the tank. Horde quest item." } },
      { id = "s3", n = "3", kind = "boss", name = { ko = "도살자(남작)", en = "The Butcher(The Baron)" }, quest = true, loot = { 271204, 271205, 271206 }, quests = { 95250, 97288 }, tip = { ko = "게임 안 이름은 '남작'. 거대한 누더기골렘이라 한 방이 아주 셉니다. 탱커 기절·띄우기·전방 베기. 부탱커를 정해 두고 딜러는 어그로 조절.", en = "Shown as The Baron in game. Huge abomination: Knockout stuns the tank, knock-up, cleave. Assign an off-tank; DPS watch threat." } },
      { id = "s4", n = "4", kind = "boss", optional = true, name = { ko = "버려진 자", en = "The Abandoned" }, loot = { 271207, 271208, 271216 }, tip = { ko = "이벤트로 나오는 숨은 우두머리. 문간에 들어서면 시작해 적이 세 차례 몰려오고 네 번째에 내려옵니다. 얼음 회오리, 생명력 흡수(차단 가능).", en = "Hidden event boss: step into the doorway, three waves, then he descends. Frost Nova and Life Drain (interruptible)." } },
      { id = "s5", n = "5", kind = "boss", name = { ko = "비요크", en = "Bjork" }, loot = { 271209, 271217, 271210 }, tip = { ko = "서쪽 시장 거리 북서쪽 안개 구역을 도는 거대한 트롤 언데드. 해골·구울이 많아 광역이 좋습니다. 대마법 보호막, 넉백. 벽을 등지고.", en = "Giant undead troll roaming the foggy NW of Market Street. Lots of trash: AoE helps. Anti-magic shell and knockback; tank on a wall." } },
      { id = "s6", n = "6", kind = "boss", name = { ko = "라스마엘", en = "Rath'mael" }, quest = true, loot = { 271213, 271214, 271215, 273085 }, quests = { 92422 }, tip = { ko = "연못 동쪽으로 내려가 울타리 친 보라색 룬 위의 마지막 우두머리. 룬에서 끌어내세요. 진짜 위험은 불기둥: 차단 순서를 정하고 놓치면 바로 피하세요.", en = "Final boss on a fenced purple rune, south past the pools. Pull him off the rune. Flamestrike is the danger: set kicks, dodge misses." } },
      { id = "s7", n = "7", kind = "boss", optional = true, name = { ko = "비열한 빅토르", en = "Viktor the Vile" }, loot = { 271211, 271212, 271218 }, tip = { ko = "숨은 우두머리. 둥근 탑 옆 벽난로에 불을 붙이면 다섯 차례 공세 뒤 나타납니다. 근접이 매우 세고 흡혈 독. 자원이 넉넉할 때 하세요.", en = "Hidden boss: light the fireplace by the round tower; five waves, then him. Hard melee and Leech Poison. Do it with resources to spare." } },
    },
    quests = {
      { id = 95250, faction = "Alliance", level = 21, name = { ko = "흉측한 괴물들", en = "Abominable Creatures" }, giver = { ko = "던전에서 남작의 머리(남작의 머리)를 가져와 대장 트루먼에게 전달", en = "Collect the Head of the Baron in the Ruins of Lordaeron and bring it back to Captain Truman." } },
      { id = 92415, faction = "Alliance", level = 22, name = { ko = "내가 사랑한다는 걸 기억해", en = "Remember That I Love You" }, giver = { ko = "피로 얼룩진 편지를 스톰윈드에 있는 보육원 원장님 나이팅게일에게 가져가야 합니다.", en = "Bring the Blood-Stained Letter to Orphan Matron Nightingale in Stormwind City." } },
      { id = 95189, faction = "Alliance", level = 22, name = { ko = "로데론의 문장", en = "Crest of Lordaeron" }, giver = { ko = "로데론의 문장을 스톰윈드에 있는 귀부인 디나 케네디에게 반환해야 합니다.", en = "Return the Crest of Lordaeron to Lady Dena Kennedy in Stormwind City." } },
      { id = 95195, faction = "Alliance", level = 22, name = { ko = "피투성이 휘장", en = "Bloodied Insignia" }, giver = { ko = "드랍된 피투성이 휘장으로 시작해 10개를 모아 스톰윈드의 장군 마커스 조나단에게", en = "Collect 10 Bloodied Insignias and take them to General Marcus Jonathan in Stormwind City." } },
      { id = 97288, faction = "Horde", level = 21, name = { ko = "끝없는 고통", en = "Unending Torment" }, giver = { ko = "흉측한 머리를 언더시티에 있는 누군가에게 전해야 합니다.", en = "Deliver the Abominable Head to someone within the Undercity." } },
      { id = 92401, faction = "Horde", level = 22, name = { ko = "두려움에 찬 부탁", en = "A Frightened Request" }, giver = { ko = "로데론의 폐허에서 에드워드 하트위버의 실종에 관해 조사해야 합니다.", en = "Investigate the disappearance of Edward Heartweaver in the Ruins of Lordaeron." } },
      { id = 92422, faction = "Horde", level = 22, name = { ko = "라스마엘의 격노", en = "The Wrath of Rath'mael" }, giver = { ko = "브릴의 죽음경비병 크리스토프를 위해 로데론의 폐허에 있는 라스마엘을 처치해야 합니다.", en = "Kill Rath'mael in the Ruins of Lordaeron for Deathguard Kristof in Brill." } },
      { id = 95204, faction = "Horde", level = 22, name = { ko = "로데론의 문장", en = "Crest of Lordaeron" }, giver = { ko = "던전 안 어딘가에 놓인 로데론의 문장(자리가 고정되지 않음)으로 시작해 언더시티의 오란 스네이크라이스에게", en = "Bring the Crest of Lordaeron to Oran Snakewrithe in Undercity." } },
      { id = 92421, faction = "Horde", level = 22, name = { ko = "빛의 정의", en = "Light's Justice" }, giver = { ko = "언더시티에 있는 모빈 라이트베인을 위해 로데론의 폐허에서 온전한 사지 25개를 수집해야 합니다.", en = "Collect 25 Intact Limbs within The Ruins of Lordaeron for Morbin Lightbane in the Undercity." } },
      { id = 95216, faction = "Horde", level = 22, name = { ko = "새로운 역병", en = "The New Plague" }, giver = { ko = "로데론의 폐허에 있는 쇠퇴송곳니에게서 맹독성 균주를 얻어 언더시티에 있는 시어도어 그리프스에게 가져가야 합니다.", en = "Collect the Highly Toxic Strain from Witherfang in Ruins of Lordaeron for Theodore Griffs in Undercity." } },
    },
    notes = { { ko = "쇠퇴송곳니가 쫄을 데리고 순찰합니다. 경로를 보고 시작하세요.", en = "Witherfang patrols with adds; watch her path." }, { ko = "'로데론의 문장'은 자리가 고정되지 않습니다. 건물 바닥을 살펴보세요.", en = "The Crest of Lordaeron has no fixed spot; check building floors." } },
  },
  {
    key = "sfk", slug = "shadowfang-keep", levels = "20-30",
    name = { ko = "그림자송곳니 성채", en = "Shadowfang Keep" },
    instanceIDs = { 33 }, nameMatch = { "그림자송곳니", "Shadowfang" },
    entrance = { map = 1421, x = 44.7, y = 67.8, zone = { ko = "은빛소나무 숲 그림자송곳니 성채", en = "Shadowfang Keep, Silverpine Forest" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 3914 }, model = 524, name = { ko = "레실고어", en = "Rethilgore" }, quest = true, loot = { 273457, 273456, 5254 }, quests = { 1098 }, tip = { ko = "첫 우두머리, 영혼 흡수. 잡은 뒤 옆 감옥에서 진영 NPC(호드 아다만트, 얼라이언스 애쉬크롬)를 풀어 주면 안뜰 문이 열립니다.", en = "First boss, Soul Drain. Then free your faction's prisoner next door (Horde Adamant, Alliance Ashcrombe) to open the courtyard." } },
      { id = "s2", n = "2", kind = "npc", optional = true, name = { ko = "죽음의추적자 빈센트", en = "Deathstalker Vincent" }, quest = true, quests = { 1098 }, tip = { ko = "'그림자송곳니 성채의 죽음의추적자'의 두 번째 죽음의추적자. 대화하면 퀘스트 완료.", en = "Second Deathstalker for Deathstalkers in Shadowfang; talk to finish." } },
      { id = "s3", n = "3", kind = "task", name = { ko = "지옥마 · 암흑마", en = "Fel Steed & Shadow Charger" }, loot = { 6341, 932, 251381 }, tip = { ko = "안뜰 마구간의 정예 말 셋. 하나를 건드리면 셋이 함께 오고, 지옥의 발구름으로 주변을 기절시킵니다.", en = "Three elite horses in the stables; pull one and all come. Fel Stomp stuns nearby." } },
      { id = "s4", n = "4", kind = "object", optional = true, name = { ko = "조던의 망치", en = "Jordan's Hammer" }, quest = true, quests = { 1654 }, tip = { ko = "성기사 퀘스트 '정의의 시험'의 조던의 망치가 여기 있습니다.", en = "Jordan's Hammer for the paladin quest The Test of Righteousness." } },
      { id = "s5", n = "5", kind = "boss", npc = { 3886 }, model = 524, name = { ko = "도살자 칼날발톱", en = "Razorclaw the Butcher" }, loot = { 1292, 6226, 6633, 273096 }, tip = { ko = "도살자의 흡수로 체력을 빼앗습니다. 탱커 체력 관리.", en = "Butcher Drain leeches health; keep the tank healed." } },
      { id = "s6", n = "6", kind = "boss", optional = true, npc = { 3887 }, model = 3222, name = { ko = "남작 실버레인", en = "Baron Silverlaine" }, loot = { 273637, 6321, 6323 }, tip = { ko = "암흑의 장막으로 받는 치유가 줄어듭니다. 저주를 해제하세요.", en = "Veil of Shadow cuts healing taken; remove the curse." } },
      { id = "s7", n = "7", kind = "boss", npc = { 4278 }, model = 3223, name = { ko = "사령관 스프링베일", en = "Commander Springvale" }, quest = true, loot = { 273643, 6320, 3191, 273105 }, quests = { 1740 }, tip = { ko = "심판의 망치로 기절시키고 성스러운 빛으로 회복합니다. 치유를 끊으세요.", en = "Stuns with Hammer of Justice and heals with Holy Light; interrupt." } },
      { id = "s8", n = "8", kind = "boss", npc = { 4279 }, model = 522, name = { ko = "눈먼감시자 오도", en = "Odo the Blindwatcher" }, loot = { 273645, 6318, 6319 }, tip = { ko = "주변 늑대인간이 죽을 때마다 강해집니다. 오도부터 잡거나 한꺼번에 처리하세요.", en = "Gets stronger as his pack dies. Focus him or kill all at once." } },
      { id = "s9", n = "9", kind = "boss", npc = { 4274 }, model = 2352, name = { ko = "파멸의 펜루스", en = "Fenrus the Devourer" }, loot = { 273646, 6340, 3230 }, tip = { ko = "맹독액으로 독을 겁니다. 독을 해제하세요.", en = "Toxic Saliva poisons; cure it." } },
      { id = "s10", n = "10", kind = "object", optional = true, name = { ko = "우르의 책", en = "The Book of Ur" }, quest = true, quests = { 1013 }, tip = { ko = "호드 퀘스트 '우르의 책'의 책이 여기 있습니다.", en = "The book for the Horde quest The Book of Ur." } },
      { id = "s11", n = "11", kind = "boss", npc = { 3927 }, model = 11179, name = { ko = "늑대왕 난도스", en = "Wolf Master Nandos" }, loot = { 273647, 3748, 6314 }, tip = { ko = "늑대를 차례로 부릅니다. 쫄을 정리하며 싸우세요.", en = "Summons worgs in turn; handle the adds as they come." } },
      { id = "s12", n = "12", kind = "boss", npc = { 4275 }, model = 2353, name = { ko = "대마법사 아루갈", en = "Archmage Arugal" }, quest = true, loot = { 6324, 6392, 6220 }, quests = { 1014 }, tip = { ko = "공허의 화살·천둥충격, 방 안을 순간이동합니다. 원거리가 계속 따라가며 공격하세요.", en = "Void Bolt, Thundershock, teleports around; ranged keep on him." } },
    },
    quests = {
      { id = 1654, faction = "Alliance", level = 22, name = { ko = "정의의 시험", en = "The Test of Righteousness" }, giver = { ko = "조던의 쪽지를 참고해 흰돌참나무 재목, 조던의 제련된 광석 상자, 조던의 대장장이 망치, 그리고 코르석을 찾아 아이언포지에 있는 조던 스틸웰에게 가져가야 합니다.", en = "Using Jordan's Weapon Notes, find some Whitestone Oak Lumber, Bailor's Refined Ore Shipment, Jordan's Smithing Hammer, and a Kor Gem, and return them to Jordan Stilwell in Ironforge." } },
      { id = 1098, faction = "Horde", level = 25, name = { ko = "그림자송곳니 성채의 죽음의추적자", en = "Deathstalkers in Shadowfang" }, giver = { ko = "죽음의추적자 아다만트와 죽음의추적자 빈센트를 찾아야 합니다.", en = "Find the Deathstalker Adamant and Deathstalker Vincent." } },
      { id = 1013, faction = "Horde", level = 26, name = { ko = "우르의 책", en = "The Book of Ur" }, giver = { ko = "언더시티의 연금술 실험실에 있는 관리인 벨두거에게 우르의 책을 가져가야 합니다.", en = "Bring the Book of Ur to Keeper Bel'dugur at the Apothecarium in the Undercity." } },
      { id = 1014, faction = "Horde", level = 27, name = { ko = "아루갈의 최후", en = "Arugal Must Die" }, giver = { ko = "아루갈을 처치하고 그 증거로 그의 머리카락을 공동묘지에 있는 달라 던위버에게 가져가야 합니다.", en = "Kill Arugal and bring his head to Dalar Dawnweaver at the Sepulcher." } },
      { id = 1740, level = 25, name = { ko = "소랜루크 수정구", en = "The Orb of Soran'ruk" }, giver = { ko = "소랜루크 조각 3개와 큰 소랜루크 조각 1개를 찾아 불모의 땅에 있는 도안 카르한에게 가져가야 합니다.", en = "Find 3 Soran'ruk Fragments and 1 Large Soran'ruk Fragment and return them to Doan Karhan in the Barrens." } },
    },
    trash = { 6642, 6641, 5943, 2292, 1974, 2807, 1935, 1483, 1318, 3194, 1484, 1489, 1482, 2205 },
    trashGroups = {
      { name = { ko = "죽음의 경비대장", en = "Deathsworn Captain" }, loot = { 6642, 6641 } },
      { name = { ko = "아루갈의 보이드워커", en = "Arugal's Voidwalker" }, loot = { 5943 } },
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 2292, 1974, 2807, 1935, 1483, 1318, 3194, 1484, 1489, 1482, 2205 }, from = { [2292] = "world", [1974] = "world", [2807] = "world", [1935] = "world", [1483] = "world", [1318] = "world", [3194] = "world", [1484] = "world", [1489] = "world", [1482] = "world", [2205] = "world" } },
    },
    notes = { { ko = "레실고어 다음 감옥에서 진영 NPC를 풀어야 안뜰 문이 열립니다.", en = "Free your faction's prisoner after Rethilgore to open the courtyard." }, { ko = "지도는 여러 층을 한 장에 겹쳐 그린 것입니다.", en = "The map flattens several floors into one." } },
  },
  {
    key = "bfd", slug = "blackfathom-deeps", levels = "24-32",
    name = { ko = "검은심연의 나락", en = "Blackfathom Deeps" },
    instanceIDs = { 48 }, nameMatch = { "검은심연", "Blackfathom" },
    entrance = { map = 1440, x = 16.5, y = 11.0, zone = { ko = "잿빛 골짜기 조람 해안의 물에 잠긴 사원", en = "Sunken temple on the Zoram Strand, Ashenvale" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 4887 }, model = 5027, name = { ko = "가무라", en = "Ghamoo-ra" }, loot = { 273839, 6907, 6908 }, tip = { ko = "밟아 뭉개기로 주변에 피해. 근접은 체력 관리.", en = "Trample hits everyone close; melee mind health." } },
      { id = "s2", n = "2", kind = "object", name = { ko = "로르갈리스 초본", en = "Lorgalis Manuscript" }, quest = true, quests = { 971 }, tip = { ko = "바닥의 책. 얼라이언스 '심연의 지식'에 필요합니다.", en = "Book on the floor for the Alliance quest Knowledge in the Deeps." } },
      { id = "s3", n = "3", kind = "boss", npc = { 4831 }, model = 4979, name = { ko = "여왕 사레베스", en = "Lady Sarevess" }, loot = { 888, 3078, 11121 }, tip = { ko = "갈래 번개·얼음 회오리·감속. 탱커 뒤에 흩어져 서세요.", en = "Forked Lightning, Frost Nova, Slow. Spread out behind the tank." } },
      { id = "s4", n = "4", kind = "npc", name = { ko = "은빛경비병 타엘리드", en = "Argent Guard Thaelrid" }, quest = true, quests = { 1198, 1200, 6561 }, tip = { ko = "안에서 만나는 은빛경비병. 대화하면 '타엘리드 찾기'가 끝나고 '검은심연의 음모'를 받습니다(양 진영).", en = "Argent Guard inside. Talk to finish his search quest and get Blackfathom Villainy (both factions)." } },
      { id = "s5", n = "5", kind = "boss", npc = { 6243 }, model = 1773, name = { ko = "겔리하스트", en = "Gelihast" }, loot = { 273840, 6906, 6905, 1470, 273141 }, tip = { ko = "그물로 발을 묶습니다. 주변 멀록부터 정리하세요.", en = "Roots with Net; clear the murlocs around him first." } },
      { id = "s6", n = "6", kind = "boss", optional = true, npc = { 12902 }, model = 12822, name = { ko = "로구스 제트", en = "Lorgus Jett" }, quest = true, loot = { 273842, 273843, 273841 }, quests = { 6565 }, tip = { ko = "자리가 고정되지 않아 여러 곳 중 하나에 나타납니다(옅은 원이 후보). 번개 보호막과 번개 화살.", en = "Spawns at one of several spots (faint circles). Lightning Shield and Lightning Bolt." } },
      { id = "s7", n = "7", kind = "boss", npc = { 4830 }, model = 1816, name = { ko = "늙은 세라키스", en = "Old Serra'kis" }, from = { 323, 407 }, loot = { 6901, 6902, 6904 }, tip = { ko = "물속에서 싸우는 상어. 수중 호흡 수단을 챙기고 숨 게이지를 보세요.", en = "Shark fought underwater. Bring water breathing, watch your breath." } },
      { id = "s8", n = "8", kind = "npc", optional = true, npc = { 12876 }, model = 110, name = { ko = "군주 아쿠아니스", en = "Baron Aquanis" }, quest = true, loot = { 16782 }, quests = { 6921, 6922 }, tip = { ko = "호드 퀘스트로 불러내는 물의 정령. 그 퀘스트가 없으면 지나가세요.", en = "Water elemental summoned for a Horde quest; skip otherwise." } },
      { id = "s9", n = "9", kind = "boss", npc = { 4832 }, model = 4939, name = { ko = "황혼의 군주 켈리스", en = "Twilight Lord Kelris" }, quest = true, from = { 154, 366 }, loot = { 273846, 1155, 6903 }, quests = { 1199, 1200, 6561 }, tip = { ko = "정신 분열과 수면. 수면 해제, 시전 차단.", en = "Mind Blast and Sleep. Dispel sleep, interrupt." } },
      { id = "s10", n = "10", kind = "task", name = { ko = "조각상 둘레 화로 정리", en = "Clear the braziers around the statue" }, tip = { ko = "켈리스를 잡고 조각상 둘레 화로 넷을 차례로 처리하면 뒤쪽 문이 열립니다.", en = "After Kelris, work through the four braziers by the statue to open the back door." } },
      { id = "s11", n = "11", kind = "boss", npc = { 4829 }, model = 2837, name = { ko = "아쿠마이", en = "Aku'mai" }, quest = true, loot = { 6911, 6910, 6909 }, quests = { 6563 }, tip = { ko = "독 구름을 깔고 체력이 낮으면 광폭해집니다. 구름에서 벗어나세요.", en = "Poison Cloud, frenzies at low health. Step out of clouds." } },
    },
    quests = {
      { id = 971, faction = "Alliance", level = 23, name = { ko = "심연의 지식", en = "Knowledge in the Deeps" }, giver = { ko = "아이언포지, 쓸쓸한 뒷골목에 있는 게릭 본그립에게 로르갈리스 초본을 가져가야 합니다.", en = "Bring the Lorgalis Manuscript to Gerrig Bonegrip in the Forlorn Cavern in Ironforge." } },
      { id = 1275, faction = "Alliance", level = 24, name = { ko = "타락에 대한 연구", en = "Researching the Corruption" }, giver = { ko = "아우버다인에 있는 게르샬라 나이트위스퍼가 변이된 뇌간 8개를 가져다 달라고 부탁했습니다.", en = "Gershala Nightwhisper in Auberdine wants 8 Corrupt Brain stems." } },
      { id = 1198, faction = "Alliance", level = 24, name = { ko = "타엘리드 찾기", en = "In Search of Thaelrid" }, giver = { ko = "검은심연의 나락에서 은빛경비병 타엘리드를 찾아야 합니다.", en = "Seek out Argent Guard Thaelrid in Blackfathom Deeps." } },
      { id = 1200, faction = "Alliance", level = 27, name = { ko = "검은심연의 음모", en = "Blackfathom Villainy" }, giver = { ko = "황혼의 군주 켈리스를 처치하고 그 증거로 머리카락을 다르나서스에 있는 새벽감시자에게 가져가야 합니다.", en = "Bring the head of Twilight Lord Kelris to Dawnwatcher Selgorm in Darnassus." } },
      { id = 1199, faction = "Alliance", level = 25, name = { ko = "황혼의망치단의 몰락", en = "Twilight Falls" }, giver = { ko = "다르나서스에 있는 은빛경비병 마나도스에게 황혼의 펜던트 10개를 가져가야 합니다.", en = "Bring 10 Twilight Pendants to Argent Guard Manados in Darnassus." } },
      { id = 6564, faction = "Horde", level = 22, name = { ko = "고대 신들에 대한 충성", en = "Allegiance to the Old Gods" }, giver = { ko = "축축한 메모를 잿빛 골짜기의 제네우 생크리에게 가져가십시오.", en = "Bring the Damp Note to Je'neu Sancrea in Ashenvale." } },
      { id = 6565, faction = "Horde", level = 26, name = { ko = "고대 신들에 대한 충성", en = "Allegiance to the Old Gods" }, giver = { ko = "검은심연의 나락에 있는 로구스 제트를 처치한 후 잿빛 골짜기의 제네우 생크리에게 돌아가십시오.", en = "Kill Lorgus Jett in Blackfathom Deeps and then return to Je'neu Sancrea in Ashenvale." } },
      { id = 6563, faction = "Horde", level = 22, name = { ko = "아쿠마이의 정수", en = "The Essence of Aku'Mai" }, giver = { ko = "잿빛 골짜기에 있는 제네우 생크리에게 아쿠마이의 사파이어 20개를 가져가야 합니다.", en = "Bring 20 Sapphires of Aku'Mai to Je'neu Sancrea in Ashenvale." } },
      { id = 6561, faction = "Horde", level = 27, name = { ko = "검은심연의 음모", en = "Blackfathom Villainy" }, giver = { ko = "황혼의 군주 켈리스를 처치하고 그 증거로 그의 머리카락을 썬더 블러프에 있는 바샤나 룬토템에게 가져가야 합니다.", en = "Bring the head of Twilight Lord Kelris to Bashana Runetotem in Thunder Bluff." } },
      { id = 6921, faction = "Horde", level = 27, name = { ko = "폐허 사이로", en = "Amongst the Ruins" }, giver = { ko = "잿빛 골짜기의 조람가르 전초기지에 있는 제네우 생크리에게 심연의 핵을 가져가야 합니다.", en = "Bring the Fathom Core to Je'neu Sancrea at Zoram'gar Outpost, Ashenvale." } },
      { id = 6922, faction = "Horde", level = 30, name = { ko = "군주 아쿠아니스", en = "Baron Aquanis" }, giver = { ko = "잿빛 골짜기의 조람가르 전초기지에 있는 제네우 생크리에게 이상한 물구슬을 가져가야 합니다.", en = "Bring the Strange Water Globe to Je'neu Sancrea at Zoram'gar Outpost, Ashenvale." } },
    },
    trash = { 2567, 3413, 1486, 3416, 1491, 3414, 1454, 1481, 3417, 3415, 2271 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 2567, 3413, 1486, 3416, 1491, 3414, 1454, 1481, 3417, 3415, 2271 }, from = { [2567] = "world", [3413] = "world", [1486] = "world", [3416] = "world", [1491] = "world", [3414] = "world", [1454] = "world", [1481] = "world", [3417] = "world", [3415] = "world", [2271] = "world" } },
    },
    notes = { { ko = "수중 구간이 있습니다. 수중 호흡 수단을 챙기세요.", en = "Underwater sections: bring water breathing." }, { ko = "지도는 세 장입니다. 창 아래 페이지 버튼으로 넘겨 보세요.", en = "Three map pages; switch with the page buttons." } },
  },
  {
    key = "stocks", slug = "stockade", levels = "24-32",
    name = { ko = "스톰윈드 지하감옥", en = "The Stockade" },
    instanceIDs = { 34 }, nameMatch = { "지하감옥", "Stockade" },
    entrance = { map = 1453, x = 50.4, y = 66.2, zone = { ko = "스톰윈드 운하 지구", en = "Canal district of Stormwind City" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 1696 }, model = 517, name = { ko = "흉악범 타고르", en = "Targorr the Dread" }, quest = true, loot = { 273804, 273805, 273806 }, quests = { 386 }, tip = { ko = "감방 몇 곳 중 한 곳에 나타납니다(옅은 원이 후보). 쌍수 난타, 체력이 낮으면 분노.", en = "Spawns in one of several cells (faint circles). Thrash, enrages low." } },
      { id = "s2", n = "2", kind = "rare", optional = true, npc = { 1720 }, model = 2142, name = { ko = "브루갈 아이언너클", en = "Bruegal Ironknuckle" }, loot = { 3228, 2941, 2942 }, tip = { ko = "감방 한 곳에 나오는 희귀 몹. 지나가도 됩니다.", en = "Rare in one of the cells. Skippable." } },
      { id = "s3", n = "3", kind = "boss", npc = { 1666 }, model = 825, name = { ko = "캄 딥퓨리", en = "Kam Deepfury" }, quest = true, loot = { 273808, 2280, 273807 }, quests = { 378 }, tip = { ko = "방어 태세에서 방패 밀쳐내기.", en = "Defensive Stance, Shield Slam." } },
      { id = "s4", n = "4", kind = "boss", npc = { 1717 }, model = 3250, name = { ko = "햄혹", en = "Hamhock" }, loot = { 273809, 273810, 273811 }, tip = { ko = "연쇄 번개와 피의 욕망. 흩어져 서세요.", en = "Chain Lightning and Bloodlust; spread out." } },
      { id = "s5", n = "5", kind = "boss", npc = { 1716 }, model = 1621, name = { ko = "바질 스레드", en = "Bazil Thredd" }, quest = true, loot = { 273825, 273829, 273824, 273827 }, quests = { 391 }, tip = { ko = "연막탄으로 기절시키고 전투의 외침.", en = "Smoke Bomb stun and Battle Shout." } },
      { id = "s6", n = "6", kind = "boss", npc = { 1663 }, model = 2149, name = { ko = "덱스트렌 워드", en = "Dextren Ward" }, quest = true, loot = { 273819, 273820, 273817 }, quests = { 377 }, tip = { ko = "위협의 외침으로 공포. 공포 걸린 사람이 옆 무리를 끌 수 있으니 주변 감방을 먼저 비우세요.", en = "Intimidating Shout fears; feared players can pull cells, so clear around first." } },
    },
    quests = {
      { id = 386, faction = "Alliance", level = 25, name = { ko = "사필귀정", en = "What Comes Around..." }, giver = { ko = "흉악범 타고르를 처치한 후 그 증거로 그의 머리카락을 레이크샤이어에 있는 경비병 베르턴에게 가져가야 합니다.", en = "Bring the head of Targorr the Dread to Guard Berton in Lakeshire." } },
      { id = 377, faction = "Alliance", level = 26, name = { ko = "죄와 벌", en = "Crime and Punishment" }, giver = { ko = "다크샤이어의 원로 밀스타이프가 덱스트렌 워드를 처치한 후 그의 장갑을 가져다 달라고 부탁했습니다.", en = "Councilman Millstipe of Darkshire wants you to bring him the hand of Dextren Ward." } },
      { id = 387, faction = "Alliance", level = 26, name = { ko = "폭동 진압", en = "Quell the Uprising" }, giver = { ko = "스톰윈드에 있는 교도소장 델워터가 지하감옥에서 데피아즈단 복역수 10명, 데피아즈단 무기징역수 8명, 데피아즈단 반역자 8명을 처치해 달라고 부탁했습니다.", en = "Warden Thelwater of Stormwind wants you to kill 10 Defias Prisoners, 8 Defias Convicts, and 8 Defias Insurgents in The Stockade." } },
      { id = 388, faction = "Alliance", level = 26, name = { ko = "피의 색", en = "The Color of Blood" }, giver = { ko = "스톰윈드에 있는 니코바 라스콜이 붉은 양모 복면을 10개를 모아 달라고 부탁했습니다.", en = "Nikova Raskol of Stormwind wants you to collect 10 Red Wool Bandanas." } },
      { id = 378, faction = "Alliance", level = 27, name = { ko = "격노", en = "The Fury Runs Deep" }, giver = { ko = "딥퓨리를 처치하고 그 증거로 그의 머리카락을 던 모드르에 있는 모틀리 가마슨에게 가져가야 합니다.", en = "Motley Garmason wants Kam Deepfury's head brought to him at Dun Modr." } },
      { id = 391, faction = "Alliance", level = 29, name = { ko = "감옥 폭동", en = "The Stockade Riots" }, giver = { ko = "바질 스레드를 처치하고 그 증거로 그의 머리카락을 감옥에 있는 교도소장 델워터에게 가져가야 합니다.", en = "Kill Bazil Thredd and bring his head back to Warden Thelwater at the Stockade." } },
    },
    trash = { 1076 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 1076 }, from = { [1076] = { { n = { ko = "데피아즈단 반역자", en = "Defias Insurgent" }, r = 1 } } } },
    },
    notes = { { ko = "죄수가 감방마다 뭉쳐 있습니다. 문 앞에서 끌어내 복도에서 잡으세요.", en = "Prisoners clump in cells; pull them into the corridor." }, { ko = "얼라이언스는 스톰윈드 안이라 오가기 쉽습니다.", en = "Easy access for the Alliance inside Stormwind." } },
  },
  {
    key = "excav", slug = "excavation-site", levels = "26-31",
    name = { ko = "발굴 현장: 저습지", en = "Excavation Site: Wetlands" },
    instanceIDs = { 2998 }, nameMatch = { "발굴 현장", "Excavation Site" },
    entrance = { map = 1437, x = 47.8, y = 56.3, zone = { ko = "저습지 웰가르의 발굴현장 남동쪽 언덕 위의 포털", en = "Portal on the hill southeast of Whelgar's Excavation Site, Wetlands" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", name = { ko = "소금가시", en = "Saltspine" }, loot = { 273022, 273023, 273024 }, tip = { ko = "잃어버린 늪의 악어 우두머리(정예 야수). 기술 정보는 아직 없습니다.", en = "Crocolisk boss of the Lost Marsh (elite beast). Abilities not known yet." } },
      { id = "s2", n = "2", kind = "boss", name = { ko = "그늘이빨", en = "Shadetooth" }, loot = { 273025, 273027, 273106, 273026 }, tip = { ko = "추적자의 숲 랩터 우두머리. 이 숲 랩터들이 '덤불 랩터 가죽'을 떨굽니다.", en = "Raptor boss of Stalker's Thicket; raptors here drop Thicket Raptor Hides." } },
      { id = "s3", n = "3", kind = "boss", name = { ko = "고원 공포", en = "Highland Horror" }, quest = true, quests = { 95646 }, tip = { ko = "늪지 괴물 정령. 선택 우두머리일 수 있습니다. 얼라이언스 퀘스트용 뿌리핵을 떨굽니다.", en = "Bog beast; may be optional. Drops the root core for an Alliance quest." } },
      { id = "s4", n = "4", kind = "boss", name = { ko = "유물 수호자", en = "Relic Guardian" }, quest = true, loot = { 273028, 273029, 273030, 273097 }, quests = { 95664, 95810 }, tip = { ko = "수호자의 터의 돌 골렘, 마지막 우두머리. 퀘스트를 시작하는 티탄의 유물을 떨굽니다.", en = "Stone golem at the Site of the Guardian, last boss. Drops the Titan Relic quest item." } },
    },
    quests = {
      { id = 98815, faction = "Alliance", level = 28, name = { ko = "고원의 가죽", en = "Highland Hides" }, giver = { ko = "덤불 랩터 가죽 4장을 메네실 항구의 무두장이 제임스 할로란에게 가져가야 합니다.", en = "Return 4 Thicket Raptor Hides to James Halloran, the tanner, in Menethil Harbor." } },
      { id = 95646, faction = "Alliance", level = 31, name = { ko = "고원의 공포", en = "Horrors in the Highland" }, giver = { ko = "발굴 현장에서 고원 공포를 처치하고 그 뿌리핵을 저습지에 있는 신록의수호자 레시엘에게 가져가야 합니다.", en = "Kill a Highland Horror within Excavation Sites and bring its root core to Rethiel the Greenwarden in the Wetlands." } },
      { id = 95647, faction = "Alliance", level = 31, name = { ko = "덤불 속 실종자", en = "Lost in the Thicket Things" }, giver = { ko = "발굴 현장에서 아르딘 그래스맨을 찾아야 합니다.", en = "Find Ardin Grassman in the Excavation Sites." } },
      { id = 95810, faction = "Alliance", level = 31, name = { ko = "잃어버린 유물 운반", en = "Lost Relic Carry" }, giver = { ko = "티탄의 유물을 저습지 발굴현장에 있는 발굴조사단장 웰가르에게 가져가야 합니다.", en = "Bring the Titan Relic to Prospector Whelgar in the Wetlands excavation site." } },
      { id = 95772, faction = "Alliance", level = 31, name = { ko = "송블레이드 찾기", en = "Songblade Search" }, giver = { ko = "웰가르의 발굴현장에서 도린 송블레이드의 형제 데윈을 찾아야 합니다.", en = "Look for Dorin Songblade's brother, Daewyn, in Whelgar's Excavation Site." } },
      { id = 95697, faction = "Horde", level = 31, name = { ko = "달라지는 입맛", en = "Changing Tastes" }, giver = { ko = "저습지의 발굴 현장에 들어가 덤불 랩터 고기 4개를 가져와야 합니다.", en = "Enter the Excavation Sites in the Wetlands and bring back Thicket Raptor Meat." } },
      { id = 95664, faction = "Horde", level = 31, name = { ko = "장로의 지식", en = "Elder Knowledge" }, giver = { ko = "티탄의 유물을 썬더 블러프의 장로의 봉우리로 가져가 그에 대해 알려 줄 사람을 찾아야 합니다.", en = "Take the Titan Relic to the Elder Rise in Thunder Bluff and look for someone who can tell you more about it." } },
      { id = 95682, level = 31, name = { ko = "용아귀 열기", en = "Open the Maw" }, giver = { ko = "발굴 현장에서 용아귀 파괴공작원 2명과 용아귀 감시병 4명을 처치하고 용아귀 급보를 가져와야 합니다.", en = "Kill 2 Dragonmaw Saboteurs and 4 Dragonmaw Warders in the Excavation Site and bring back the Dragonmaw Dispatch." } },
    },
    notes = { { ko = "만남의 돌은 저습지 53.4, 65.3입니다.", en = "Meeting stone: Wetlands 53.4, 65.3." }, { ko = "추적자의 숲에 정예 랩터가 많습니다.", en = "Many elite raptors in Stalker's Thicket." } },
  },
  {
    key = "dala", slug = "dalaran", levels = "28-33",
    name = { ko = "달라란", en = "City of Dalaran" },
    instanceIDs = { 2959 }, nameMatch = { "달라란", "Dalaran" },
    steps = {
      { id = "s1", n = "1", kind = "boss", name = { ko = "무덤 기사 아트렉시스", en = "Atrexis the Grave Knight" }, quest = true, loot = { 273036 }, quests = { 96986 }, tip = { ko = "하수도 지나 지하 의식의 원, 키린 토 강령술사들과 함께. 해골이 계속 일어나지만 약하니 나오는 대로 잡고, 탱커 무장 해제에 대비. 호드 퀘스트 '무덤 기사' 대상.", en = "Ritual Circle in the Underbelly with Kirin Tor Necromancers. Weak skeletons keep rising: kill them as they come. Disarms the tank. Horde quest The Grave Knight." } },
      { id = "s7", n = "2", kind = "boss", optional = true, name = { ko = "외면받는 린", en = "Lyn the Ignored" }, tip = { ko = "희귀 우두머리. 하수도 작은 원형 방의 의식진에서 달라란의 책을 쓰면 나옵니다(만드는 법은 준비 탭).", en = "Rare boss: use the Tome of Dalaran on the ritual circle in the sewers' small round room (how to make it: Prep tab)." } },
      { id = "s2", n = "3", kind = "boss", name = { ko = "비전 변형물", en = "Arcane Anomaly" }, tip = { ko = "둥근 테라스의 거품에서 끌려 나옵니다. 3초 시전 뒤 정면으로 6초 광선(집중 폭발): 시전이 보이면 바로 앞에서 비키세요. 사이사이 탱커에게 비전 화살.", en = "Pulled from a bubble on the Round Terrace. After a 3s cast, Focal Blast beams straight ahead for 6s: get out of its front. Arcane Bolt on the tank in between." } },
      { id = "s3", n = "4", kind = "boss", name = { ko = "지옥의 고대정령", en = "Fel Ancient" }, loot = { 273038, 273039 }, tip = { ko = "지옥 기운 스민 나무정령들 사이. 덩굴(지옥 목재)이 한 명에게 뻗어 주변 5미터를 치고 독 연기를 남기니 연기 밖으로 나가세요.", en = "Among Suffused Treants. Fel Timbers hits everyone within 5 yd of one player and leaves poison fumes: move out." } },
      { id = "s6", n = "5", kind = "boss", name = { ko = "마나 정령", en = "Arcanic Enigma" }, aliases = { "Mana Elemental", "Arcanic Enigma", "마나 정령" }, quest = true, loot = { 273045 }, quests = { 92489 }, tip = { ko = "게임 안 이름 비전의 수수께끼. 8초 변이(마법이라 해제 가능)와 10초 침묵이 있어 치유사는 떨어져 있으세요. 작은 마나 정령을 계속 불러내니 광역으로. 얼라이언스 '압도적인 힘' 대상.", en = "Named Arcanic Enigma. Manamorph (8s, magic: dispel) and a 10s silence: healers keep distance. Keeps calling Arcane Manalings: AoE them. Alliance quest Power Overwhelming." } },
      { id = "s4", n = "6", kind = "boss", name = { ko = "불안정한 파수꾼", en = "Unstable Sentinel" }, loot = { 273046, 273047, 273099 }, tip = { ko = "마법 거래소. 가는 길에 달려드는 성난 마법서를 먼저 잡으세요. 2초 시전 뒤 6초간 25미터 광역(오작동): 원거리는 25미터 밖, 근접은 시전 중에 빠지기.", en = "Magus Commerce Exchange; kill the Angry Tomes on the way first. After a 2s cast Malfunction pulses within 25 yd for 6s: ranged stay out, melee step out." } },
      { id = "s9", n = "7", kind = "boss", name = { ko = "대마법사의 망령", en = "Shade of the Archmage" }, loot = { 273051, 273052 }, tip = { ko = "보랏빛 성채 응접실. 마나 구슬이 한 명에게 갔다 돌아오며 길목에 비전 피해와 6초 침묵: 우두머리와 그 사람 사이에 서지 마세요. 마나가 바닥나면 파티 전체 8초 변이 뒤 6초 환기. 전투 중 누가 방을 나가면 체력이 다 찹니다.", en = "In the Purple Parlor of the Violet Citadel. Bounding Mana flies to a player and back, silencing anyone in its path: don't stand between them. Out of mana he polymorphs the group (8s), then Evocation (6s). Leaving the room resets him." } },
      { id = "s5", n = "8", kind = "boss", name = { ko = "마나 포식자", en = "Mana Devourer" }, loot = { 273040, 273041, 273042 }, tip = { ko = "남쪽 분수 정원의 북쪽 끝(큰 주황 돔 위쪽). 기술 정보는 아직 없습니다.", en = "North end of the southern fountain garden (above the big orange dome). Abilities unknown yet." } },
    },
    quests = {
      { id = 92456, faction = "Alliance", level = 33, name = { ko = "녹색 표본", en = "A Green Sample" }, giver = { ko = "달라란에서 지옥 마력이 주입된 꽃을 구해 스톰윈드에 있는 샤이라미르에게 가져가야 합니다.", en = "Collect a Fel Infused Blossom from the City of Dalaran for Shylamiir in Stormwind City." } },
      { id = 92458, faction = "Alliance", level = 33, name = { ko = "혼란의 심장", en = "Heart of Disruption" }, giver = { ko = "달라란 근처의 대마법사 모데라의 환영를 위해 달라란에서 비전 티끌를 구해야 합니다. 이 퀘스트를 받으면 달라란 하수도 열쇠를 줍니다.", en = "Collect the Arcane Mote for the Image of Archmage Modera near the City of Dalaran. Taking it gives you the Dalaran Sewer Key." } },
      { id = 92489, faction = "Alliance", level = 33, name = { ko = "압도적인 힘", en = "Power Overwhelming" }, giver = { ko = "스톰윈드에 있는 고위마술사 안드로매스를 위해 달라란에서 마나 정령을 처치해야 합니다.", en = "Slay the Mana Elemental in the City of Dalaran for High Sorcerer Andromath in Stormwind City." } },
      { id = 96984, faction = "Horde", level = 33, name = { ko = "혼란의 심장", en = "Heart of Disruption" }, giver = { ko = "타렌 밀농장에 있는 마법학자 워딘 보이드글레어를 위해 달라란에서 비전 티끌를 구해야 합니다. 이 퀘스트를 받으면 달라란 하수도 열쇠를 줍니다.", en = "Collect the Arcane Mote in the City of Dalaran for Magus Wordeen Voidglare in Tarren Mill. Taking it gives you the Dalaran Sewer Key." } },
      { id = 96987, faction = "Horde", level = 33, name = { ko = "배움의 기회", en = "Opportunistic Education" }, giver = { ko = "하수도 입구 근처에 있는 렉시 코퍼클러치를 위해 달라란에서 달라란 건국사를 구해야 합니다.", en = "Collect the Founding of Dalaran from the City of Dalaran for Rexxie Copperclutch near the sewer entrance." } },
      { id = 96986, faction = "Horde", level = 33, name = { ko = "무덤 기사", en = "The Grave Knight" }, giver = { ko = "타렌 밀농장에 있는 멜리사라를 위해 달라란에서 무덤 기사 아트렉시스를 쓰러뜨려야 합니다.", en = "Defeat Atrexis the Grave Knight in the City of Dalaran for Melisara in Tarren Mill." } },
      { id = 96988, faction = "Horde", level = 33, name = { ko = "힘의 원천", en = "Source of Power" }, giver = { ko = "언더시티에 있는 박사 마틴 펠벤을 위해 달라란에서 금이 간 파수꾼 핵 6개를 모아야 합니다.", en = "Collect 6 Cracked Sentry Cores in the City of Dalaran for Doctor Martin Felben in Undercity." } },
      { id = 92457, level = 33, name = { ko = "굶주린 비전", en = "Starving Arcane" }, giver = { ko = "달라란 밖에 있는 대마법사 모데라를 위해 달라란 안에서 갈구하는 잔재 8마리, 충만한 잔재 8마리, 마나 메아리 8마리를 처치해야 합니다.", en = "Defeat 8 Seeking Remnants, 8 Saturated Remnants, and 8 Mana Echoes inside the City of Dalaran for Archmage Modera outside of Dalaran." } },
    },
    trash = { 273043 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 273043 } },
    },
    notes = { { ko = "권장 28~33레벨이고 던전 퀘스트는 24레벨부터 받습니다.", en = "Levels 28-33; dungeon quests from level 24." }, { ko = "입구는 하수도를 지나 긴 관 끝의 차원문. 하수도 문은 입장 퀘스트로 받는 달라란 하수도 열쇠로 열고, 입장 퀘스트를 마친 사람이 파티에 한 명 있으면 모두 들어갑니다.", en = "Entrance: the portal at the end of a long pipe through the sewers. The sewer door needs the Dalaran Sewer Key from the attunement; one attuned member lets the whole group in." }, { ko = "얼라이언스 입장: 힐스브래드 사절 자크 '불길한 요청'(30레벨~) → 은빛소나무 숲 동쪽 끝 대마법사 모데라의 환영 '혼란의 심장'(열쇠) → 보랏빛 성채 대마법사 셀린드라 '키린 토의 친구'.", en = "Alliance attunement: An Alarming Request (Emissary Jacques, Hillsbrad, from 30) → Heart of Disruption (Image of Archmage Modera, east Silverpine; gives the key) → Friend of the Kirin Tor (Archmage Celindra)." }, { ko = "호드 입장: 타렌 밀농장 마법학자 워딘 보이드글레어의 다른 퀘스트를 끝낸 뒤 '거리에 흐르는 피'(30레벨~) → '혼란의 심장' → 대마법사 셀린드라 '빈틈없는 협상'.", en = "Horde attunement: finish Magus Wordeen Voidglare's other quests in Tarren Mill, then Blood in the Streets (from 30) → Heart of Disruption → Shrewd Negotiations (Archmage Celindra)." }, { ko = "희귀 외면받는 린: 그림자송곳니 성채 아루갈 뒤의 검은 고서을 은빛소나무 숲 앰버밀(63.4, 64.3)의 수정에 쓰면 달라란의 책이 됩니다.", en = "Rare Lyn the Ignored: use the Black Tome (behind Arugal, Shadowfang Keep) on the crystal at Ambermill, Silverpine (63.4, 64.3) to make the Tome of Dalaran." }, { ko = "하수도에서 시작해 도시로 올라갑니다. 하수도와 도시를 별도 미니맵으로 표시하며, 연결 표식을 누르면 다른 구역으로 전환합니다. 보스 표식은 공략 자료를 참고한 위치입니다.", en = "The run starts in the sewers and climbs to the city. The floors have separate native minimaps and reciprocal clickable guide links. Boss markers are registered guide reference positions." } },
  },
  {
    key = "gnomer", slug = "gnomeregan", levels = "29-38",
    name = { ko = "놈리건", en = "Gnomeregan" },
    instanceIDs = { 90 }, nameMatch = { "놈리건", "Gnomeregan" },
    entrance = { map = 1426, x = 17.7, y = 39.2, zone = { ko = "던 모로 서쪽 놈리건 정문", en = "The front gate of Gnomeregan in western Dun Morogh" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 7361 }, model = 6533, name = { ko = "그루비스", en = "Grubbis" }, loot = { 9445, 274042, 274043 }, tip = { ko = "폭발물전문가 에미에게 말을 걸면 에미가 입구를 폭파하는 동안 트로그가 몰려오고 끝에 그루비스가 나옵니다. 에미를 지키세요.", en = "Talk to Blastmaster Emi: troggs rush in while she seals the tunnels, then Grubbis comes. Keep Emi alive." } },
      { id = "s2", n = "2", kind = "boss", npc = { 7079 }, model = 5497, name = { ko = "방사성 폐기물", en = "Viscous Fallout" }, quest = true, loot = { 9454, 9453, 9452 }, quests = { 2962 }, tip = { ko = "방사능 구역의 우두머리. 근처 방사능 몹에게서 얼라이언스 '유일한 치료법'의 폐기물을 얻습니다.", en = "Boss of the irradiated zone. Mobs here give the fallout for the Alliance quest The Only Cure is More Green Glow." } },
      { id = "s3", n = "3", kind = "npc", name = { ko = "케르노비", en = "Kernobee" }, quest = true, quests = { 2904 }, tip = { ko = "케르노비를 찾아 태엽장치 통로 출구까지 호위하세요('곤경에 빠진 케르노비'). 서 있는 자리는 여러 곳 중 하나.", en = "Find Kernobee and escort him to the Clockwerk Run exit (A Fine Mess). He stands at one of several spots." } },
      { id = "s4", n = "4", kind = "object", optional = true, name = { ko = "삐까뻔쩍세척기 5200", en = "The Sparklematic 5200" }, quest = true, quests = { 2930, 2945, 2951 }, tip = { ko = "정화 지역의 세척기. 꼬질꼬질한 반지를 넣어 닦습니다. 근처에 천공기록기 3005-B.", en = "Sparklematic in the Clean Zone: clean the Grime-Encrusted Ring here. Punchograph 3005-B is nearby." } },
      { id = "s5", n = "5", kind = "boss", npc = { 6235 }, model = 6915, name = { ko = "기계화 문지기 6000", en = "Electrocutioner 6000" }, quest = true, loot = { 9447, 9446, 9448, 6893 }, quests = { 2930 }, tip = { ko = "전격·연쇄 벼락·100만 볼트. 흩어져 서세요. 작업장 열쇠를 떨구고, 방에 천공기록기 3005-C.", en = "Shock, Chain Bolt, Megavolt. Spread out. Drops the Workshop Key; Punchograph 3005-C in his room." } },
      { id = "s6", n = "6", kind = "boss", npc = { 6229 }, model = 6774, name = { ko = "고철 압축기 9-60", en = "Crowd Pummeler 9-60" }, quest = true, loot = { 9449, 9450, 274049, 274068 }, quests = { 2930 }, tip = { ko = "회전 강타·밟아 뭉개기·고철 압축으로 주변을 칩니다. 근접은 옆·뒤, 원거리는 멀리. 출격실에 3005-D.", en = "Arcing Smash, Trample, Crowd Pummel hit all around. Melee at sides/back, ranged far. Punchograph 3005-D in the bay." } },
      { id = "s7", n = "7", kind = "rare", optional = true, npc = { 6228 }, model = 6669, name = { ko = "검은무쇠단 사절", en = "Dark Iron Ambassador" }, loot = { 9455, 9456, 9457 }, tip = { ko = "희귀 몹. 화염구, 화염 보호막·냉기 갑옷, 불타는 하수인 소환. 지나가도 됩니다.", en = "Rare: Fireball, Fire Shield, Frost Armor, summons a servant. Skippable." } },
      { id = "s8", n = "8", kind = "npc", optional = true, name = { ko = "검은무쇠단 첩보원", en = "Dark Iron Agent" }, quest = true, quests = { 2945 }, tip = { ko = "첩보원이 떨구는 꼬질꼬질한 반지로 같은 이름의 퀘스트가 시작됩니다. 여러 곳에 나옵니다.", en = "Agents drop the Grime-Encrusted Ring that starts its quest. Found in many places." } },
      { id = "s9", n = "9", kind = "boss", npc = { 7800 }, model = 6980, name = { ko = "멕기니어 텔마플러그", en = "Mekgineer Thermaplugg" }, quest = true, loot = { 9461, 9458, 4415, 4413, 4411, 7742, 9492, 9459 }, quests = { 2841, 2929 }, tip = { ko = "날려버리기로 탱커를 밀칩니다. 방 둘레 놈 얼굴 장치에서 폭탄 로봇이 나오니 장치를 누르거나 로봇을 먼저 처리.", en = "Knock Away on the tank. Bombs walk out of the gnome-face machines; press them or kill bombs first." } },
      { id = "s10", n = "10", kind = "object", optional = true, name = { ko = "텔마플러그의 금고", en = "Thermaplugg's Safe" }, quest = true, quests = { 2841 }, tip = { ko = "호드 '기술 전쟁'의 설계도가 든 금고. 비밀번호는 텔마플러그가 떨굽니다.", en = "Safe with the blueprints for the Horde quest Rig Wars; Thermaplugg drops the code." } },
    },
    quests = {
      { id = 2962, faction = "Alliance", level = 30, name = { ko = "유일한 치료법", en = "The Only Cure is More Green Glow" }, giver = { ko = "놈리건으로 가서 고농축 방사성 폐기물을 가져와야 합니다. 이 폐기물은 불안정하여 성분이 금방 변할 수 있으니 주의하십시오. 임무를 완수한 후 빈 대형 가연채집병을 오지에게 돌려줘야 합니다.", en = "Travel to Gnomeregan and bring back High Potency Radioactive Fallout. Be warned, the fallout is unstable and will collapse rather quickly. Ozzie will also require your Heavy Leaden Collection Phial when the task is complete." } },
      { id = 2930, faction = "Alliance", level = 30, name = { ko = "자료 회수", en = "Data Rescue" }, giver = { ko = "아이언포지에 있는 수석수리공 캐스트파이프에게 오색 천공 카드를 가져가야 합니다.", en = "Bring a Prismatic Punch Card to Master Mechanic Castpipe in Ironforge." } },
      { id = 2924, faction = "Alliance", level = 30, name = { ko = "필수 인공장치", en = "Essential Artificials" }, giver = { ko = "아이언포지에 있는 클락몰트 스패너스판에게 필수 인공장치 12개를 가져가야 합니다.", en = "Bring 12 Essential Artificials to Klockmort Spannerspan in Ironforge." } },
      { id = 2928, faction = "Alliance", level = 30, name = { ko = "회전천공식 발굴기", en = "Gyrodrillmatic Excavationators" }, giver = { ko = "스톰윈드에 있는 쇼니에게 기계장치 부속품 24개를 가져가야 합니다.", en = "Bring twenty-four Robo-mechanical Guts to Shoni in Stormwind." } },
      { id = 2929, faction = "Alliance", level = 35, name = { ko = "대배반", en = "The Grand Betrayal" }, giver = { ko = "놈리건으로 가서 멕기니어 텔마플러그를 처치해야 합니다. 임무가 끝나면 땜장이왕 멕카토크에게 돌아와야 합니다.", en = "Venture to Gnomeregan and kill Mekgineer Thermaplugg. Return to High Tinker Mekkatorque when the task is complete." } },
      { id = 95041, faction = "Alliance", name = { ko = "자료 수집광", en = "Data Hoarders" }, giver = { ko = "놈리건 전역의 놈리건 보관 자료 카드 7장을 수집한 후, 아이언포지에 있는 젬마 퀵스위치에게 전달해야 합니다.", en = "Collect 7 Gnomeregan Archival Data cards from around Gnomeregan, then deliver them to Jemma Quikswitch in Ironforge." } },
      { id = 2841, faction = "Horde", level = 35, name = { ko = "기술 전쟁", en = "Rig Wars" }, giver = { ko = "놈리건에서 장치 설계도와 텔마플러그의 금고 암호를 찾아서 오그리마에 있는 노그에게 가져다주어야 합니다.", en = "Retrieve the Rig Blueprints and Thermaplugg's Safe Combination from Gnomeregan and bring them to Nogg in Orgrimmar." } },
      { id = 2904, level = 30, name = { ko = "곤경에 빠진 케르노비", en = "A Fine Mess" }, giver = { ko = "태엽장치 통로 입구까지 케르노비를 호위한 후 무법항에 있는 스쿠티에게 가서 보고해야 합니다.", en = "Escort Kernobee to the Clockwerk Run exit and then report to Scooty in Booty Bay." } },
      { id = 2951, level = 30, name = { ko = "삐까뻔쩍세척기 5200!", en = "The Sparklematic 5200!" }, giver = { ko = "삐까뻔쩍세척기 5200에 꼬질꼬질한 물건을 넣으십시오. 3실버를 투입하면 작동할 것입니다.", en = "Insert a Grime-Encrusted Item into the Sparklematic 5200, and be sure to have three silver coins to start the machine." } },
      { id = 2945, level = 34, name = { ko = "꼬질꼬질한 반지", en = "Grime-Encrusted Ring" }, giver = { ko = "꼬질꼬질한 반지에서 찌꺼기를 제거할 방법을 찾아야 합니다.", en = "Figure out a way to remove the grime from the Grime-Encrusted Ring." } },
    },
    trash = { 9491, 9510, 9488, 9486, 11827, 9444, 9508, 9509, 9487, 9485, 9490, 9489, 11826, 9327, 7191, 9308, 9326, 9279, 9280, 9282, 9281, 9316, 6672, 7192, 7560 },
    trashGroups = {
      { name = { ko = "첨단로봇", en = "Techbot" }, loot = { 9444 } },
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 11827, 9327, 7191, 9326, 9491, 9510, 9488, 9486, 9508, 9509, 9487, 9485, 9490, 9489, 9308, 11826, 9279, 9280, 9282, 9281, 9316, 6672, 7192, 7560 }, from = { [11827] = { { n = { ko = "고철 압축기 9-60", en = "Crowd Pummeler 9-60" }, r = 2 } }, [9327] = { { n = { ko = "평화감시단 방사능처리반", en = "Peacekeeper Security Suit" }, r = 2.94 }, { n = { ko = "기계화 보초병", en = "Mechanized Sentry" }, r = 2.62 }, { n = { ko = "기계보행전차", en = "Mechano-Tank" }, r = 2.32 }, { n = { ko = "기계박사 텔마플러그", en = "Mekgineer Thermaplugg" }, r = 1 }, { n = { ko = "기계화 문지기 6000", en = "Electrocutioner 6000" }, r = 1 }, { n = { ko = "고철 압축기 9-60", en = "Crowd Pummeler 9-60" }, r = 1 } }, [7191] = { { n = { ko = "평화감시단 방사능처리반", en = "Peacekeeper Security Suit" }, r = 2.64 } }, [9326] = { { n = { ko = "검은무쇠단 첩보원", en = "Dark Iron Agent" }, r = 10 } }, [9491] = "world", [9510] = "world", [9488] = "world", [9486] = "world", [9508] = "world", [9509] = "world", [9487] = "world", [9485] = "world", [9490] = "world", [9489] = "world", [9308] = "world" } },
    },
    notes = { { ko = "천공 카드 퀘스트: 흰 카드를 3005 기계에 차례로 넣습니다. A는 밖, B·C·D는 안.", en = "Punch card quest: feed the card into the 3005 machines (A outside, B/C/D inside)." }, { ko = "기계화 문지기 6000의 작업장 열쇠로 다음부터 뒷문으로 들어올 수 있습니다.", en = "Electrocutioner's Workshop Key opens the back entrance next time." } },
  },
  {
    key = "rfk", slug = "razorfen-kraul", levels = "29-38",
    name = { ko = "가시덩굴 우리", en = "Razorfen Kraul" },
    instanceIDs = { 47 }, nameMatch = { "가시덩굴 우리", "Razorfen Kraul" },
    entrance = { map = 1413, x = 42.3, y = 89.9, zone = { ko = "불모의 땅 남쪽 끝 가시덤불 속", en = "In the brambles at the southern tip of The Barrens" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 6168 }, model = 6110, name = { ko = "루구그", en = "Roogug" }, quest = true, loot = { 274152, 274155, 274149 }, quests = { 1701, 1838 }, tip = { ko = "번개 화살과 바위 정령 소환. 정령부터 잡으세요. 전사 퀘스트용 연소 약병을 떨굽니다.", en = "Lightning Bolt, summons an Earth Rumbler; kill it first. Drops the warrior quest vial." } },
      { id = "s2", n = "2", kind = "boss", npc = { 4424 }, model = 6097, name = { ko = "저주의가시 아겜", en = "Aggem Thorncurse" }, loot = { 6681, 274159, 274158 }, tip = { ko = "전투의 외침, 멧돼지 정령 소환, 연쇄 치유. 치유를 끊으세요.", en = "Battle Shout, boar spirits, Chain Heal. Interrupt heals." } },
      { id = "s3", n = "3", kind = "boss", npc = { 4428 }, model = 4644, name = { ko = "죽음의예언자 잘그바", en = "Death Speaker Jargba" }, loot = { 2816, 6685, 6682 }, tip = { ko = "어둠의 화살과 정신 지배. 조종당한 사람은 묶어 두고 잘그바부터.", en = "Shadow Bolt and Dominate Mind. CC the controlled player, focus Jargba." } },
      { id = "s4", n = "4", kind = "boss", npc = { 4420 }, model = 4652, name = { ko = "대군주 램터스크", en = "Overlord Ramtusk" }, loot = { 6687, 6686, 274161 }, tip = { ko = "천둥벼락과 전투의 외침. 곁에 가시근위병이 붙어 있습니다.", en = "Thunderclap, Battle Shout; a Spearhide stands next to him." } },
      { id = "s5", n = "5", kind = "rare", optional = true, name = { ko = "가시덩굴일족 가시근위병", en = "Razorfen Spearhide" }, loot = { 6679 }, tip = { ko = "램터스크 곁의 정예. 가시 오라와 소용돌이 탄막.", en = "Elite beside Ramtusk: Thorns Aura, Whirling Barrage." } },
      { id = "s6", n = "6", kind = "rare", optional = true, npc = { 4842 }, model = 6102, name = { ko = "대지의주술사 함가르", en = "Earthcaller Halmgar" }, loot = { 6688, 6689 }, tip = { ko = "희귀 몹. 바위 정령 소환, 속박의 토템, 번개 화살. 지나가도 됩니다.", en = "Rare: Earth Rumbler, Earthbind Totem, Lightning Bolt. Skippable." } },
      { id = "s7", n = "7", kind = "boss", npc = { 4422 }, model = 2450, name = { ko = "흉포한 아가테로스", en = "Agathelos the Raging" }, loot = { 6691, 6690, 274160 }, tip = { ko = "맹렬한 돌진, 분노·격노. 탱커가 단단히 잡아 두세요.", en = "Rushing Charge, Enrage, Rampage. Tank must hold him firmly." } },
      { id = "s8", n = "8", kind = "rare", optional = true, npc = { 4425 }, model = 4735, name = { ko = "눈먼사냥꾼", en = "Blind Hunter" }, quest = true, loot = { 6695, 6697, 6696 }, quests = { 1109 }, tip = { ko = "박쥐 동굴의 희귀 몹. 이 박쥐들이 호드 '조분석을 나에게!'의 조분석을 떨굽니다.", en = "Rare in the bat cave; the bats drop guano for the Horde quest." } },
      { id = "s9", n = "9", kind = "npc", name = { ko = "수입업자 윌릭스", en = "Willix the Importer" }, quest = true, quests = { 1142, 1144, 1221 }, tip = { ko = "갇혀 있는 윌릭스. 입구까지 호위하면 퀘스트 완료. 청엽수 줄기 자리도 이 근처에 많습니다.", en = "Willix is held here; escort him to the entrance. Many Blueleaf Tuber spots nearby." } },
      { id = "s10", n = "10", kind = "npc", name = { ko = "헤랄라스 팰로우브룩", en = "Heralath Fallowbrook" }, quest = true, quests = { 1142 }, tip = { ko = "헤랄라스의 주검. 얼라이언스 '꺼져가는 생명의 불씨'를 받습니다.", en = "Heralath's body gives the Alliance quest Mortality Wanes." } },
      { id = "s11", n = "11", kind = "boss", npc = { 4421 }, model = 4642, name = { ko = "서슬깃 차를가", en = "Charlga Razorflank" }, quest = true, loot = { 6692, 6693, 6694, 17008 }, quests = { 1101, 1102 }, tip = { ko = "연쇄 벼락·마나 쐐기, 소생으로 회복. 흩어져 서고 소생을 해제하세요. 퀘스트용 메달·심장을 떨굽니다.", en = "Chain Bolt, Mana Spike, heals with Renew. Spread out and dispel Renew. Drops quest medallion/heart." } },
    },
    quests = {
      { id = 1701, faction = "Alliance", level = 28, name = { ko = "불에 달궈 만든 갑옷", en = "Fire Hardened Mail" }, giver = { ko = "스톰윈드에 있는 푸렌 롱비어드에게 그가 필요로 하는 재료들을 모아서 가져가야 합니다.", en = "Gather the materials Furen Longbeard requires, and bring them to him in Stormwind." } },
      { id = 1142, faction = "Alliance", level = 30, name = { ko = "꺼져가는 생명의 불씨", en = "Mortality Wanes" }, giver = { ko = "트레샬라의 펜던트를 찾아 다르나서스에 있는 트레샬라 팰로우브룩에게 돌려주어야 합니다.", en = "Find and return Treshala's Pendant to Treshala Fallowbrook in Darnassus." } },
      { id = 1101, faction = "Alliance", level = 34, name = { ko = "가시덩굴 우리의 대모", en = "The Crone of the Kraul" }, giver = { ko = "탈라나르에 있는 팔핀델 웨이워더에게 차를가의 메달을 가져가야 합니다.", en = "Bring Razorflank's Medallion to Falfindel Waywarder in Thalanaar." } },
      { id = 1838, faction = "Horde", level = 30, name = { ko = "투사의 방어구", en = "Brutal Armor" }, giver = { ko = "툰그림 파이어게이즈에게 연기나는 철제 주괴 15개, 아주라이트 가루 10개, 철 주괴 10개, 연소 약병 1개를 가져가야 합니다.", en = "Bring to Thun'grim Firegaze 15 Smoky Iron Ingots, 10 Powdered Azurite, 10 Iron Bars and a Vial of Phlogiston." } },
      { id = 1109, faction = "Horde", level = 33, name = { ko = "조분석을 나에게!", en = "Going, Going, Guano!" }, giver = { ko = "언더시티에 있는 수석 연금술사 파라넬에게 가시덩굴 조분석을 가져가야 합니다.", en = "Bring 1 pile of Kraul Guano to Master Apothecary Faranell in the Undercity." } },
      { id = 1102, faction = "Horde", level = 34, name = { ko = "운명의 복수", en = "A Vengeful Fate" }, giver = { ko = "썬더 블러프에 있는 아울드 스톤스파이어에게 차를가의 심장을 가져가야 합니다.", en = "Bring Razorflank's Heart to Auld Stonespire in Thunder Bluff." } },
      { id = 1221, level = 26, name = { ko = "청엽수 줄기", en = "Blueleaf Tubers" }, giver = { ko = "구멍 난 상자를 집어야 합니다. 땅다람쥐 지휘봉도 챙겨야 합니다. 땅다람쥐 설명서를 찾아서 읽어야 합니다. 가시덩굴 우리에서 구멍 난 상자를 사용해 땅다람쥐를 소환하고 지휘봉을 사용해 땅다람쥐에게 청엽수 줄기를 찾아내도록 해야 합니다. 톱니항에 있는 메보크 미지릭스에게 청엽수 줄기 6개와 사용한 땅다람쥐 지휘봉과 구멍 난 상자를 가져가야 합니다.", en = "Grab a Crate with Holes. Grab a Snufflenose Command Stick. Grab and read the Snufflenose Owner's Manual. In Razorfen Kraul, use the Crate with Holes to summon a Snufflenose Gopher, and use the Command Stick on the gopher to make it search for Tubers. Bring 6 Blueleaf Tubers, the Snufflenose Command Stick and the Crate with Holes to Mebok Mizzyrix in Ratchet." } },
      { id = 1144, level = 30, name = { ko = "수입업자 윌릭스", en = "Willix the Importer" }, giver = { ko = "수입업자 윌릭스를 호위해 가시덩굴 우리에서 나가야 합니다.", en = "Escort Willix the Importer out of Razorfen Kraul." } },
    },
    trash = { 2264, 4438, 1978, 2039, 1976, 2549, 1488, 1727, 776, 1975 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 2264, 4438, 1978, 2039, 1976, 2549, 1488, 1727, 776, 1975 }, from = { [2264] = "world", [4438] = "world", [1978] = "world", [2039] = "world", [1976] = "world", [2549] = "world", [1488] = "world", [1727] = "world", [776] = "world", [1975] = "world" } },
    },
    notes = { { ko = "아겜과 차를가는 스스로 치유합니다. 차단을 준비하세요.", en = "Aggem and Charlga heal themselves; have interrupts." }, { ko = "청엽수 줄기 퀘스트는 들어오기 전에 톱니항에서 상자·지휘봉·설명서를 챙기세요.", en = "Blueleaf Tubers: grab crate, stick and manual in Ratchet first." } },
  },
  {
    key = "smgy", slug = "scarlet-monastery-graveyard", levels = "30-38",
    name = { ko = "붉은십자군 수도원 묘지", en = "Scarlet Monastery Graveyard" },
    instanceIDs = { 189 }, nameMatch = { "묘지", "Graveyard" },
    subzones = { "속죄의 방", "쓸쓸한 회랑", "명예의 무덤", "묘지", "Chamber of Atonement", "Forlorn Cloister", "Honor's Tomb", "Graveyard" }, resetNames = { "붉은십자군 수도원", "Scarlet Monastery" },
    entrance = { map = 1420, x = 85.1, y = 31.4, zone = { ko = "티리스팔 숲 동쪽 끝 붉은십자군 수도원", en = "The Scarlet Monastery at the eastern end of Tirisfal Glades" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 3983 }, model = 2044, name = { ko = "심문관 비샤스", en = "Interrogator Vishas" }, quest = true, loot = { 7682, 7683, 274290 }, quests = { 1113 }, tip = { ko = "어둠의 권능: 고통과 제물. 해제 가능하면 해제하세요.", en = "Shadow Word: Pain and Immolate; dispel if you can." } },
      { id = "s2", n = "2", kind = "npc", name = { ko = "보렐 센구츠", en = "Vorrel Sengutz" }, quest = true, quests = { 1051 }, tip = { ko = "비샤스 방에 갇혀 있습니다. 호드 '보렐의 복수'(결혼반지를 타렌 밀농장으로).", en = "Held in Vishas' room. Horde quest Vorrel's Revenge (ring to Tarren Mill)." } },
      { id = "s3", n = "3", kind = "rare", optional = true, npc = { 6488, 6489, 6490 }, group = true, model = 5230, name = { ko = "잠들지 않는 아즈쉬르 · 타락한 용사 · 무쇠해골", en = "Azshir the Sleepless · Fallen Champion · Ironspine" }, loot = { 7709, 7708, 7731, 7691, 7690, 7689, 7688, 7687, 7686 }, tip = { ko = "잠들지 않는 아즈쉬르·타락한 용사·무쇠해골 중 하나가 여러 자리 중 한 곳에 나옵니다(옅은 원이 후보).", en = "One of Azshir the Sleepless, Fallen Champion or Ironspine spawns at one of several spots (faint circles)." } },
      { id = "s4", n = "4", kind = "boss", npc = { 4543 }, model = 11396, name = { ko = "혈법사 탈노스", en = "Bloodmage Thalnos" }, loot = { 7685, 7684, 274291 }, tip = { ko = "불의 쐐기·불꽃 회오리·화염 충격·어둠의 화살. 근접은 체력을 넉넉히. 묘지 끝 지하에 있습니다.", en = "Flame Spike, Fire Nova, Flame Shock, Shadow Bolt. Melee keep health up. In the crypt at the end." } },
    },
    quests = {
      { id = 1051, faction = "Horde", level = 33, name = { ko = "보렐의 복수", en = "Vorrel's Revenge" }, giver = { ko = "타렌 밀농장에 있는 모니카 센구츠에게 보렐의 결혼반지를 가져가야 합니다.", en = "Return Vorrel Sengutz's wedding ring to Monika Sengutz in Tarren Mill." } },
      { id = 1113, faction = "Horde", level = 33, name = { ko = "열정의 증거", en = "Hearts of Zeal" }, giver = { ko = "언더시티에 있는 수석 연금술사 파라넬에게 열정의 증거 20개를 가져가야 합니다.", en = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal." } },
    },
    trash = { 7754, 10332, 7752, 7786, 7730, 5819, 7727, 7728, 2262, 7787, 7729, 7761, 8226, 7753 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 7754, 10332, 7752, 7786, 7730, 5819, 7727, 7728, 2262, 7787, 7729, 7761, 8226, 7753 }, from = { [7754] = "world", [10332] = "world", [7752] = "world", [7786] = "world", [7730] = "world", [5819] = "world", [7727] = "world", [7728] = "world", [2262] = "world", [7787] = "world", [7729] = "world", [7761] = "world", [8226] = "world", [7753] = "world" } },
    },
    notes = { { ko = "수도원 날개 넷은 입구와 인스턴스가 따로입니다. 보통 묘지→도서관→무기고→대성당 순.", en = "Four wings, separate entrances. Usual order: GY, Library, Armory, Cathedral." } },
  },
  {
    key = "smlib", slug = "scarlet-monastery-library", levels = "33-41",
    name = { ko = "붉은십자군 수도원 도서관", en = "Scarlet Monastery Library" },
    instanceIDs = { 189 }, nameMatch = { "도서관", "Library" },
    subzones = { "사냥꾼의 회랑", "보물 전시실", "도서관", "Huntsman's Cloister", "Gallery of Treasures", "Athenaeum", "The Athenaeum", "Library" }, resetNames = { "붉은십자군 수도원", "Scarlet Monastery" },
    entrance = { map = 1420, x = 85.1, y = 31.4, zone = { ko = "티리스팔 숲 동쪽 끝 붉은십자군 수도원", en = "The Scarlet Monastery at the eastern end of Tirisfal Glades" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 3974 }, model = 2040, name = { ko = "사냥개조련사 록시", en = "Houndmaster Loksey" }, quest = true, loot = { 7710, 7756, 3456, 274292 }, quests = { 1048, 1053, 1113 }, tip = { ko = "사냥개와 함께 싸우며 피의 욕망·전투의 외침. 개부터 잡거나 광역으로.", en = "Fights with hounds, Bloodlust and Battle Shout. Dogs first or AoE." } },
      { id = "s2", n = "2", kind = "object", optional = true, name = { ko = "티탄 신화", en = "Mythology of the Titans" }, quest = true, quests = { 1050 }, tip = { ko = "서고 책장의 '티탄 신화'(얼라이언스 퀘스트).", en = "Mythology of the Titans on the shelves (Alliance quest)." } },
      { id = "s3", n = "3", kind = "object", optional = true, name = { ko = "언데드 위협의 기원", en = "Beginnings of the Undead Threat" }, quest = true, quests = { 1160 }, tip = { ko = "호드 '지혜의 시험'의 책 '언데드 위협의 기원'.", en = "The Beginnings of the Undead Threat for the Horde quest Test of Lore." } },
      { id = "s4", n = "4", kind = "object", optional = true, name = { ko = "타락의 개요", en = "Compendium of the Fallen" }, quest = true, quests = { 1049 }, tip = { ko = "'타락의 개요'(호드 퀘스트).", en = "Compendium of the Fallen (Horde quest)." } },
      { id = "s5", n = "5", kind = "object", optional = true, name = { ko = "마력의 의식", en = "Rituals of Power" }, quest = true, quests = { 1951 }, tip = { ko = "'마력의 의식'(마법사 퀘스트).", en = "Rituals of Power (mage quest)." } },
      { id = "s6", n = "6", kind = "boss", npc = { 6487 }, model = 5266, name = { ko = "신비술사 도안", en = "Arcanist Doan" }, loot = { 7714, 7713, 7711, 7712, 274293 }, tip = { ko = "침묵·신비한 폭발. 체력 절반에 거품을 두르고 주변을 변이시킨 뒤 폭발하니, 거품이 보이면 바로 멀리. 뒤쪽 금고에 붉은십자군 열쇠.", en = "Silence, Arcane Explosion. At half he bubbles, polymorphs nearby, then detonates: run when you see the bubble. Scarlet Key in the strongbox behind." } },
    },
    quests = {
      { id = 96800, faction = "Alliance", level = 38, name = { ko = "반납 기한 초과", en = "Past Due" }, giver = { ko = "붉은십자군 수도원에서 룬 대가의 잃어버린 마법 책을 가져와야 합니다.", en = "Retrieve the book The Lost Magic of the Runemasters from the Scarlet Monastery." } },
      { id = 1050, faction = "Alliance", level = 38, name = { ko = "티탄 신화", en = "Mythology of the Titans" }, giver = { ko = "수도원에서 티탄 신화라는 책을 찾아 아이언포지에 있는 사서 메이 페일더스트에게 가져가야 합니다.", en = "Retrieve Mythology of the Titans from the Monastery and bring it to Librarian Mae Paledust in Ironforge." } },
      { id = 1053, faction = "Alliance", level = 40, name = { ko = "빛의 이름으로!", en = "In the Name of the Light" }, giver = { ko = "종교재판관 화이트메인, 붉은십자군 사령관 모그레인, 붉은십자군 용사 헤로드와 사냥개조련사 록시를 처치한 후 사우스쇼어에 있는 경건한 신자 랄레이에게 돌아가 보고하십시오.", en = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Raleigh the Devout in Southshore." } },
      { id = 1113, faction = "Horde", level = 33, name = { ko = "열정의 증거", en = "Hearts of Zeal" }, giver = { ko = "언더시티에 있는 수석 연금술사 파라넬에게 열정의 증거 20개를 가져가야 합니다.", en = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal." } },
      { id = 1160, faction = "Horde", level = 36, name = { ko = "지혜의 시험", en = "Test of Lore" }, giver = { ko = "언데드 위협의 기원을 찾아 언더시티에 있는 파쿠알 핀탈라스에게 가져가야 합니다.", en = "Find The Beginnings of the Undead Threat, and return it to Parqual Fintallas in Undercity." } },
      { id = 1049, faction = "Horde", level = 38, name = { ko = "타락의 개요", en = "Compendium of the Fallen" }, giver = { ko = "티리스팔 숲의 붉은십자군 수도원에서 타락의 개요를 찾아 썬더 블러프에 있는 현자 트루스시커에게 가져가야 합니다.", en = "Retrieve the Compendium of the Fallen from the Monastery in Tirisfal Glades and return to Sage Truthseeker in Thunder Bluff." } },
      { id = 1048, faction = "Horde", level = 42, name = { ko = "붉은십자군 수도원으로", en = "Into The Scarlet Monastery" }, giver = { ko = "종교재판관 화이트메인, 붉은십자군 사령관 모그레인, 붉은십자군 용사 헤로드와 사냥개조련사 록시를 처치한 후 언더시티에 있는 바리마트라스에게 돌아가 보고해야 합니다.", en = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Varimathras in the Undercity." } },
      { id = 1951, level = 40, name = { ko = "마력의 의식", en = "Rituals of Power" }, giver = { ko = "먼지진흙 습지대에 있는 타베사에게 마력의 의식을 가져가야 합니다.", en = "Bring the book Rituals of Power to Tabetha in Dustwallow Marsh." } },
    },
    trash = { 7754, 10332, 7752, 7786, 7730, 7757, 5819, 7755, 7727, 7728, 7759, 7760, 1992, 2262, 7787, 7729, 7761, 8226, 5756, 7736, 8225, 7753, 7758 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 7754, 10332, 7752, 7786, 7730, 7757, 5819, 7755, 7727, 7728, 7759, 7760, 1992, 2262, 7787, 7729, 7761, 8226, 5756, 7736, 8225, 7753, 7758 }, from = { [7754] = "world", [10332] = "world", [7752] = "world", [7786] = "world", [7730] = "world", [7757] = "world", [5819] = "world", [7755] = "world", [7727] = "world", [7728] = "world", [7759] = "world", [7760] = "world", [1992] = "world", [2262] = "world", [7787] = "world", [7729] = "world", [7761] = "world", [8226] = "world", [5756] = "world", [7736] = "world", [8225] = "world", [7753] = "world", [7758] = "world" } },
    },
    notes = { { ko = "서고에서 줍는 책: 티탄 신화(얼), 타락의 개요(호), 언데드 위협의 기원(호), 마력의 의식(마법사).", en = "Books here: Titans (A), Compendium (H), Undead Threat (H), Rituals (mage)." } },
  },
  {
    key = "smarm", slug = "scarlet-monastery-armory", levels = "36-44",
    name = { ko = "붉은십자군 수도원 무기고", en = "Scarlet Monastery Armory" },
    instanceIDs = { 189 }, nameMatch = { "무기고", "Armory" },
    subzones = { "훈련장", "보병 무기고", "십자군 무기고", "용사의 전당", "Training Grounds", "Footman's Armory", "Crusader's Armory", "Hall of Champions", "Armory" }, resetNames = { "붉은십자군 수도원", "Scarlet Monastery" },
    entrance = { map = 1420, x = 85.1, y = 31.4, zone = { ko = "티리스팔 숲 동쪽 끝 붉은십자군 수도원", en = "The Scarlet Monastery at the eastern end of Tirisfal Glades" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 3975 }, model = 2041, name = { ko = "헤로드", en = "Herod" }, quest = true, loot = { 7719, 10330, 7717 }, quests = { 1048, 1053, 1113 }, tip = { ko = "회전베기·소용돌이, 체력이 낮으면 분노. 소용돌이 땐 근접도 물러서세요. 쓰러지면 수련생 무리가 몰려오니 모여서 광역으로.", en = "Cleave and Whirlwind, enrages low. Step back during Whirlwind. Trainees rush in on his death; group up and AoE." } },
    },
    quests = {
      { id = 1053, faction = "Alliance", level = 40, name = { ko = "빛의 이름으로!", en = "In the Name of the Light" }, giver = { ko = "종교재판관 화이트메인, 붉은십자군 사령관 모그레인, 붉은십자군 용사 헤로드와 사냥개조련사 록시를 처치한 후 사우스쇼어에 있는 경건한 신자 랄레이에게 돌아가 보고하십시오.", en = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Raleigh the Devout in Southshore." } },
      { id = 1113, faction = "Horde", level = 33, name = { ko = "열정의 증거", en = "Hearts of Zeal" }, giver = { ko = "언더시티에 있는 수석 연금술사 파라넬에게 열정의 증거 20개를 가져가야 합니다.", en = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal." } },
      { id = 1048, faction = "Horde", level = 42, name = { ko = "붉은십자군 수도원으로", en = "Into The Scarlet Monastery" }, giver = { ko = "종교재판관 화이트메인, 붉은십자군 사령관 모그레인, 붉은십자군 용사 헤로드와 사냥개조련사 록시를 처치한 후 언더시티에 있는 바리마트라스에게 돌아가 보고해야 합니다.", en = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Varimathras in the Undercity." } },
    },
    trash = { 7754, 10332, 7752, 7786, 7730, 7757, 10333, 10329, 5819, 7755, 7727, 7728, 7759, 1992, 2262, 7787, 7729, 7761, 8226, 5756, 7736, 8225, 7753 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 10333, 10329, 7754, 10332, 7752, 7786, 7730, 7757, 5819, 7755, 7727, 7728, 7759, 1992, 2262, 7787, 7729, 7761, 8226, 5756, 7736, 8225, 7753 }, from = { [10333] = { { n = { ko = "붉은십자군 수호병", en = "Scarlet Protector" }, r = 2 }, { n = { ko = "붉은십자군 보초", en = "Scarlet Guardsman" }, r = 2 } }, [10329] = { { n = { ko = "붉은십자군 호위병", en = "Scarlet Defender" }, r = 2 }, { n = { ko = "붉은십자군 정예병", en = "Scarlet Myrmidon" }, r = 2 } }, [7754] = "world", [10332] = "world", [7752] = "world", [7786] = "world", [7730] = "world", [7757] = "world", [5819] = "world", [7755] = "world", [7727] = "world", [7728] = "world", [7759] = "world", [1992] = "world", [2262] = "world", [7787] = "world", [7729] = "world", [7761] = "world", [8226] = "world", [5756] = "world", [7736] = "world", [8225] = "world", [7753] = "world" } },
    },
    notes = { { ko = "헤로드가 소용돌이를 돌 때 원거리와 힐러는 떨어져 서세요.", en = "Ranged and healers stay away during Herod's Whirlwind." } },
  },
  {
    key = "rfd", slug = "razorfen-downs", levels = "37-46",
    name = { ko = "가시덩굴 구릉", en = "Razorfen Downs" },
    instanceIDs = { 129 }, nameMatch = { "가시덩굴 구릉", "Razorfen Downs" },
    entrance = { map = 1413, x = 50.8, y = 92.8, zone = { ko = "불모의 땅 남쪽 끝, 가시덩굴 우리 동쪽", en = "At the southern tip of The Barrens, east of Razorfen Kraul" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 7355 }, model = 7845, name = { ko = "투텐카쉬", en = "Tuten'kash" }, loot = { 10775, 10777 }, tip = { ko = "징을 울리면 나타납니다. 거미줄로 묶고 저주를 걸며 근접 공격에 독이 묻어납니다.", en = "Ring the gong to summon it. Web Spray roots, curse, poisonous melee." } },
      { id = "s2", n = "2", kind = "boss", unconfirmed = true, npc = { 7356 }, model = 6124, name = { ko = "썩어가는 역병아귀", en = "Plaguemaw the Rotting" }, tip = { ko = "고약한 냄새와 부패의 손길. (위치 미확인)", en = "Putrid Stench and Withered Touch. (Location unconfirmed)" } },
      { id = "s3", n = "3", kind = "boss", npc = { 7357 }, model = 8055, name = { ko = "불꽃눈 모드레쉬", en = "Mordresh Fire Eye" }, loot = { 10771, 10770 }, tip = { ko = "화염구와 불꽃 회오리.", en = "Fireball and Fire Nova." } },
      { id = "s4", n = "4", kind = "boss", npc = { 7354 }, model = 11382, name = { ko = "너덜주둥이", en = "Ragglesnout" }, tip = { ko = "어둠의 화살·고통, 치유, 정신 지배. 치유를 끊으세요.", en = "Shadow Bolt, SW:Pain, heals and Dominate Mind. Interrupt heals." } },
      { id = "s5", n = "5", kind = "boss", npc = { 8567 }, model = 7864, name = { ko = "게걸먹보", en = "Glutton" }, loot = { 10774, 10772 }, tip = { ko = "질병 구름을 두르고 난타, 분노하면 더 세집니다.", en = "Disease Cloud, Thrash, hits harder when enraged." } },
      { id = "s6", n = "6", kind = "boss", npc = { 7358 }, model = 7971, name = { ko = "혹한의 암네나르", en = "Amnennar the Coldbringer" }, loot = { 10763, 10762, 10764, 10761, 10765 }, tip = { ko = "얼음 화살·얼음 회오리·암네나르의 격노, 냉기 갑옷, 냉기 유령 소환.", en = "Frostbolt, Frost Nova, Amnennar's Wrath, Frost Armor, summons spectres." } },
    },
    trash = { 10574, 10581, 10583, 10584, 10578, 10582, 10572, 10567, 10571, 10570, 10573 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 10574, 10581, 10583, 10584, 10578, 10582, 10572, 10567, 10571, 10570, 10573 }, from = { [10574] = "world", [10581] = "world", [10583] = "world", [10584] = "world", [10578] = "world", [10582] = "world", [10572] = "world", [10567] = "world", [10571] = "world", [10570] = "world", [10573] = "world" } },
    },
    notes = { { ko = "25레벨부터 입장할 수 있습니다.", en = "Entry from level 25." } },
  },
  {
    key = "smcath", slug = "scarlet-monastery-cathedral", levels = "38-46",
    name = { ko = "붉은십자군 수도원 대성당", en = "Scarlet Monastery Cathedral" },
    instanceIDs = { 189 }, nameMatch = { "대성당", "Cathedral" },
    subzones = { "예배당 정원", "십자군 예배당", "대성당", "Chapel Gardens", "Crusader's Chapel", "Cathedral" }, resetNames = { "붉은십자군 수도원", "Scarlet Monastery" },
    entrance = { map = 1420, x = 85.1, y = 31.4, zone = { ko = "티리스팔 숲 동쪽 끝 붉은십자군 수도원", en = "The Scarlet Monastery at the eastern end of Tirisfal Glades" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 4542 }, model = 2605, name = { ko = "종교재판관 페어뱅크스", en = "High Inquisitor Fairbanks" }, loot = { 19507, 19508, 19509 }, tip = { ko = "치유·보호막·마법 무효화로 버티고 피의 저주·공포·수면. 치유를 끊으세요.", en = "Heals, shields, dispels; Curse of Blood, Fear, Sleep. Interrupt heals." } },
      { id = "s2", n = "2", kind = "boss", npc = { 3976 }, model = 2042, name = { ko = "붉은십자군 사령관 모그레인", en = "Scarlet Commander Mograine" }, quest = true, loot = { 7724, 10330, 7726, 7723 }, quests = { 1048, 1053, 1113 }, tip = { ko = "예배당 제단 앞. 응보의 오라, 성전사의 일격, 심판의 망치, 위험하면 천상의 보호막. 쓰러뜨리면 화이트메인이 나옵니다.", en = "At the chapel altar. Retribution Aura, Crusader Strike, HoJ, Divine Shield. Killing him brings Whitemane." } },
      { id = "s3", n = "3", kind = "boss", npc = { 3977 }, model = 2043, name = { ko = "종교재판관 화이트메인", en = "High Inquisitor Whitemane" }, quest = true, loot = { 7721 }, quests = { 1048, 1053, 1113 }, tip = { ko = "성스러운 일격·치유·보호막. 체력 절반에 모두를 재우고 모그레인을 되살립니다. 그때를 위해 체력과 마나를 남겨 두세요.", en = "Holy Smite, heals, shields. At half she sleeps everyone and revives Mograine; save health and mana for it." } },
    },
    quests = {
      { id = 1053, faction = "Alliance", level = 40, name = { ko = "빛의 이름으로!", en = "In the Name of the Light" }, giver = { ko = "종교재판관 화이트메인, 붉은십자군 사령관 모그레인, 붉은십자군 용사 헤로드와 사냥개조련사 록시를 처치한 후 사우스쇼어에 있는 경건한 신자 랄레이에게 돌아가 보고하십시오.", en = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Raleigh the Devout in Southshore." } },
      { id = 1113, faction = "Horde", level = 33, name = { ko = "열정의 증거", en = "Hearts of Zeal" }, giver = { ko = "언더시티에 있는 수석 연금술사 파라넬에게 열정의 증거 20개를 가져가야 합니다.", en = "Master Apothecary Faranell in the Undercity wants 20 Hearts of Zeal." } },
      { id = 1048, faction = "Horde", level = 42, name = { ko = "붉은십자군 수도원으로", en = "Into The Scarlet Monastery" }, giver = { ko = "종교재판관 화이트메인, 붉은십자군 사령관 모그레인, 붉은십자군 용사 헤로드와 사냥개조련사 록시를 처치한 후 언더시티에 있는 바리마트라스에게 돌아가 보고해야 합니다.", en = "Kill High Inquisitor Whitemane, Scarlet Commander Mograine, Herod, the Scarlet Champion and Houndmaster Loksey and then report back to Varimathras in the Undercity." } },
    },
    trash = { 7754, 10332, 7752, 7786, 7730, 7757, 10328, 10331, 10329, 5819, 7755, 7727, 7728, 7759, 7760, 1992, 2262, 7787, 7729, 7761, 8226, 5756, 7736, 8225, 7753, 7758 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 10328, 10331, 10329, 7754, 10332, 7752, 7786, 7730, 7757, 5819, 7755, 7727, 7728, 7759, 7760, 1992, 2262, 7787, 7729, 7761, 8226, 5756, 7736, 8225, 7753, 7758 }, from = { [10328] = { { n = { ko = "붉은십자군 용사", en = "Scarlet Champion" }, r = 0.5 } }, [10331] = { { n = { ko = "붉은십자군 백인대장", en = "Scarlet Centurion" }, r = 2 } }, [10329] = { { n = { ko = "붉은십자군 호위병", en = "Scarlet Defender" }, r = 2 }, { n = { ko = "붉은십자군 정예병", en = "Scarlet Myrmidon" }, r = 2 } }, [7754] = "world", [10332] = "world", [7752] = "world", [7786] = "world", [7730] = "world", [7757] = "world", [5819] = "world", [7755] = "world", [7727] = "world", [7728] = "world", [7759] = "world", [7760] = "world", [1992] = "world", [2262] = "world", [7787] = "world", [7729] = "world", [7761] = "world", [8226] = "world", [5756] = "world", [7736] = "world", [8225] = "world", [7753] = "world", [7758] = "world" } },
    },
    notes = { { ko = "대성당 들어가기 전, 정원 무리를 문 앞으로 끌어 따로 잡으세요. 예배당 몹을 같이 끌면 모그레인이 합세합니다.", en = "Pull courtyard packs to the door; pulling chapel mobs brings Mograine." } },
  },
  {
    key = "ulda", slug = "uldaman", levels = "41-51",
    name = { ko = "울다만", en = "Uldaman" },
    instanceIDs = { 70 }, nameMatch = { "울다만", "Uldaman" },
    entrance = { map = 1418, x = 35.2, y = 10.7, zone = { ko = "황야의 땅 북쪽 끝", en = "At the northern edge of the Badlands" } },
    steps = {
      { id = "s1", n = "1", kind = "boss", npc = { 6910 }, model = 5945, name = { ko = "레벨로쉬", en = "Revelosh" }, loot = { 9389, 9388, 9390, 9387 }, tip = { ko = "번개 화살과 연쇄 번개.", en = "Lightning Bolt and Chain Lightning." } },
      { id = "s2", n = "2", kind = "boss", npc = { 6906, 6907, 6908 }, model = 5710, name = { ko = "길 잃은 드워프", en = "The Lost Dwarves" }, tip = { ko = "밸로그(사격·일격)·에릭(돌진)·올라프(방패 밀쳐내기·완벽 방어) 셋과 함께 싸웁니다.", en = "Baelog (Shoot, Strike), Eric (Rushing Charge) and Olaf (Shield Slam, 100% Block) together." } },
      { id = "s3", n = "3", kind = "boss", unconfirmed = true, npc = { 7228 }, model = 6089, name = { ko = "아이로나야", en = "Ironaya" }, loot = { 9409, 9407 }, tip = { ko = "날려버리기·전투 발구르기·회전 강타. 기존 서버 이벤트 소환 위치 참고.", en = "Knock Away, War Stomp, Arcing Smash. Historical event summon reference." } },
      { id = "s4", n = "4", kind = "boss", npc = { 7023 }, model = 5285, name = { ko = "흑요석 파수꾼", en = "Obsidian Sentinel" }, tip = { ko = "주문 반사와 흑요석 파편 소환.", en = "Spell Reflection and Obsidian Shards." } },
      { id = "s5", n = "5", kind = "boss", npc = { 7206 }, model = 10798, name = { ko = "고대 바위 문지기", en = "Ancient Stone Keeper" }, loot = { 9411 }, tip = { ko = "모래 폭풍을 일으킵니다.", en = "Summons Sand Storms." } },
      { id = "s6", n = "6", kind = "boss", npc = { 7291 }, model = 6059, name = { ko = "갈간 파이어해머", en = "Galgann Firehammer" }, tip = { ko = "화염 채찍·화염 충격·불꽃 회오리, 화염계 증폭.", en = "Flame Lash, Flame Shock, Fire Nova, Amplify Flames." } },
      { id = "s7", n = "7", kind = "boss", npc = { 4854 }, model = 11165, name = { ko = "그림로크", en = "Grimlok" }, loot = { 9415, 9416, 9414 }, tip = { ko = "번개 화살·연쇄 벼락·축소, 피의 욕망.", en = "Lightning Bolt, Chain Bolt, Shrink, Bloodlust." } },
      { id = "s8", n = "8", kind = "boss", npc = { 2748 }, model = 5988, name = { ko = "아카에다스", en = "Archaedas" }, tip = { ko = "제단을 쓰면 깨어납니다. 지진, 방 둘레 석상들을 깨워 싸움에 끌어들입니다.", en = "Wakes when you use the altar. Ground Tremor; awakens the statues around the room." } },
    },
    trash = { 9431, 9429, 9420, 9430, 9397, 9406, 9428, 9432, 9396, 9393, 9381, 9426, 9422, 9465, 9384, 9386, 9427, 9392, 9424, 9383, 9425, 9423, 9391 },
    trashGroups = {
      { name = { ko = "일반 몹", en = "Trash mobs" }, trash = true, loot = { 9431, 9429, 9420, 9430, 9397, 9406, 9428, 9432, 9396, 9393, 9381, 9426, 9422, 9465, 9384, 9386, 9427, 9392, 9424, 9383, 9425, 9423, 9391 }, from = { [9431] = "world", [9429] = "world", [9420] = "world", [9430] = "world", [9397] = "world", [9406] = "world", [9428] = "world", [9432] = "world", [9396] = "world", [9393] = "world", [9381] = "world", [9426] = "world", [9422] = "world", [9465] = "world", [9384] = "world", [9386] = "world", [9427] = "world", [9392] = "world", [9424] = "world", [9383] = "world", [9425] = "world", [9423] = "world", [9391] = "world" } },
    },
    notes = { { ko = "30레벨부터 입장할 수 있습니다.", en = "Entry from level 30." } },
  },
}

ns.DungeonByKey = {}
for _, d in ipairs(ns.Dungeons) do ns.DungeonByKey[d.key] = d end
