# Tips rewritten for Dungeon Route Guide (facts from wowf.io guides, own wording).
# TIPS[slug][n] = (ko, en)
# NOTES[slug] = [(ko, en), ...]   preparation notes

TIPS = {
"ragefire-chasm": {
 1: ("입구 복도 끝 갈림길입니다. 서쪽으로 가서 오글플린트부터 잡고, 나중에 이 자리로 돌아옵니다.",
     "Junction at the end of the entrance corridor. Go west for Oggleflint first; you return here later."),
 2: ("회전베기를 씁니다. 탱커 말고는 정면을 피하세요.", "Cleaves, so only the tank stands in front."),
 3: ("용암 옆 오르막 끝 막다른 굴에 있는 시체입니다. '잃어버린 가방 찾기'의 가방을 여기서 줍습니다.",
     "Corpse in a dead-end nook up the lava path. Loot the satchel for Searching for the Lost Satchel."),
 4: ("왔던 길로 다시 갈림길에 돌아와, 이번엔 남쪽 길로 올라갑니다.", "Back at the junction, take the southern path up this time."),
 5: ("불꽃 회오리로 주변 전체를 태우고 올려치기로 탱커를 띄웁니다. 근접은 체력을 넉넉히. 심장은 '야수 처단' 퀘스트 아이템.",
     "Fire Nova hits everyone close and Uppercut launches the tank. Melee keep health up. His heart is for Slaying the Beast."),
 6: ("타라가만 다음, 서쪽 가장자리 길로 돌아 올라가면 있습니다. 사악한 일격과 독. 독을 해제하세요.",
     "After Taragaman, loop up the western edge. Sinister Strike and poison; cure it."),
 7: ("바잘란 자리에서 절벽 아래로 뛰어내리면 바로 앞입니다. 제물과 무력화 저주. 저주 해제, 시전 차단.",
     "Jump down the cliff from Bazzalan's ledge and you land on him. Immolate and Curse of Weakness: decurse and interrupt."),
},
"wailing-caverns": {
 1: ("던전 입구 앞 바깥 동굴(날팍 근처)에 숨은 정예입니다. '99년 묵은 와인'의 포트 와인을 떨구니 들어가기 전에 잡으세요.",
     "Elite hiding in the outer cave by Nalpak. Drops the port for Trouble at the Docks; kill him before zoning in."),
 2: ("번개 화살·수면·치유의 손길, 가시 오라. 치유는 꼭 끊으세요. 송곳니의 군주 넷 중 하나.",
     "Lightning Bolt, Sleep, Healing Touch and Thorns. Always kick the heal. One of the four Fanglords."),
 3: ("치유를 쓰다가 뱀으로 변해 독을 겁니다. 치유 차단, 독 해제. 송곳니의 군주.",
     "Heals, then turns into a serpent that poisons. Interrupt heals, cure poison. A Fanglord."),
 4: ("기술 없는 거북. 물길을 따라 천천히 돌아다니니 끌어와서 잡으면 됩니다.", "Harmless turtle wandering the water. Just pull it."),
 5: ("번개 화살·수면·천둥벼락·치유. 치유를 끊으세요. 송곳니의 군주.", "Lightning Bolt, Sleep, Thunderclap and heals. Kick the heals. A Fanglord."),
 6: ("사슬 번개를 쓰고 체력이 낮으면 도망칩니다. 달아나지 못하게 붙잡으세요.", "Chained Bolt; runs at low health, so stop him fleeing."),
 7: ("동쪽 굴을 떠도는 희귀 몹. 보이면 잡고 없으면 지나가세요.", "Rare wandering the eastern caves. Kill if up, else move on."),
 8: ("번개 화살·수면·치유. 치유 차단. 송곳니의 군주 마지막.", "Lightning Bolt, Sleep, heals. Kick heals. The last Fanglord."),
 9: ("휘감는 덩굴로 주변을 넘어뜨립니다. 힐러는 거리를 두세요.", "Grasping Vines knocks down everyone close; healers stay back."),
 10: ("송곳니의 군주 넷이 죽으면 제자가 의식을 하러 움직입니다. 따라가며 몰려오는 몹을 잡고 지켜 주세요.",
      "With the four Fanglords dead the Disciple starts his ritual walk. Follow and protect him from the waves."),
 11: ("호위가 끝나면 나타납니다. 공포·천둥균열·수면(나랄렉스의 악몽). '빛나는 조각'이 나올 수 있어요.",
      "Appears after the escort. Terrify, Thundercrack and a sleep. May drop The Glowing Shard."),
},
"deadmines": {
 1: ("격돌로 탱커를 기절시킵니다. 기절한 동안 힐러가 체력을 채워 주세요.", "Slam stuns the tank; healer tops them up meanwhile."),
 2: ("옆길 작은 방의 희귀 정예. 건너뛰어도 됩니다.", "Rare elite in a side room. Skippable."),
 3: ("스니드의 벌목기를 먼저 부수면 스니드가 튀어나옵니다. 무장 해제를 씁니다.", "Break Sneed's Shredder and he jumps out. He disarms."),
 4: ("용해된 금속을 뿌리고 제련공들이 합류합니다. 쫄부터 정리하세요.", "Molten Metal; smelters join the fight. Clear adds first."),
 5: ("제련소 옆 화약 더미. '죽음의 폐광 파괴 작전'의 폭발물은 이 근처 숨은 가열로에 설치합니다.",
     "Gunpowder by the foundry. Plant the explosives for Destruction in Deadmines at the hidden forge here."),
 6: ("여기부터 배입니다. 체력이 줄면 발구르기로 파티를 기절시키고 상자에서 무기를 바꿉니다. 기절이 풀리면 다시 모이세요.",
     "The ship starts here. At health thresholds he stuns everyone and swaps weapons at his chest; regroup after."),
 7: ("갑판 아래 주방. 요리로 자신을 치유하고 산성 물질을 끼얹습니다. 요리를 끊으세요.", "Galley below deck. Heals himself by cooking and splashes acid; interrupt the cooking."),
 8: ("독 묻은 작살과 회전베기. 독을 해제하고 탱커 뒤에 서세요.", "Poisoned Harpoon and Cleave. Cure poison, stand behind."),
 9: ("배 뒤쪽 윗갑판의 마지막 우두머리. 쌍수 난타, 체력이 줄면 호위병을 부릅니다. 쫄은 묶거나 먼저 잡으세요. '부치지 않은 편지'를 챙기세요.",
     "Final boss on the upper deck aft. Thrash, then calls guards as he weakens; control or kill them. Grab The Unsent Letter."),
},
"shadowfang-keep": {
 1: ("첫 우두머리, 영혼 흡수. 잡은 뒤 옆 감옥에서 진영 NPC(호드 아다만트, 얼라이언스 애쉬크롬)를 풀어 주면 안뜰 문이 열립니다.",
     "First boss, Soul Drain. Then free your faction's prisoner next door (Horde Adamant, Alliance Ashcrombe) to open the courtyard."),
 2: ("'그림자송곳니 성채의 죽음의추적자'의 두 번째 죽음의추적자. 대화하면 퀘스트 완료.", "Second Deathstalker for Deathstalkers in Shadowfang; talk to finish."),
 3: ("안뜰 마구간의 정예 말 셋. 하나를 건드리면 셋이 함께 오고, 지옥의 발구름으로 주변을 기절시킵니다.",
     "Three elite horses in the stables; pull one and all come. Fel Stomp stuns nearby."),
 4: ("성기사 퀘스트 '정의의 시험'의 조던의 망치가 여기 있습니다.", "Jordan's Hammer for the paladin quest The Test of Righteousness."),
 5: ("도살자의 흡수로 체력을 빼앗습니다. 탱커 체력 관리.", "Butcher Drain leeches health; keep the tank healed."),
 6: ("암흑의 장막으로 받는 치유가 줄어듭니다. 저주를 해제하세요.", "Veil of Shadow cuts healing taken; remove the curse."),
 7: ("심판의 망치로 기절시키고 성스러운 빛으로 회복합니다. 치유를 끊으세요.", "Stuns with Hammer of Justice and heals with Holy Light; interrupt."),
 8: ("주변 늑대인간이 죽을 때마다 강해집니다. 오도부터 잡거나 한꺼번에 처리하세요.", "Gets stronger as his pack dies. Focus him or kill all at once."),
 9: ("맹독액으로 독을 겁니다. 독을 해제하세요.", "Toxic Saliva poisons; cure it."),
 10: ("호드 퀘스트 '우르의 책'의 책이 여기 있습니다.", "The book for the Horde quest The Book of Ur."),
 11: ("늑대를 차례로 부릅니다. 쫄을 정리하며 싸우세요.", "Summons worgs in turn; handle the adds as they come."),
 12: ("공허의 화살·천둥충격, 방 안을 순간이동합니다. 원거리가 계속 따라가며 공격하세요.", "Void Bolt, Thundershock, teleports around; ranged keep on him."),
},
"blackfathom-deeps": {
 1: ("밟아 뭉개기로 주변에 피해. 근접은 체력 관리.", "Trample hits everyone close; melee mind health."),
 2: ("바닥의 책. 얼라이언스 '심연의 지식'에 필요합니다.", "Book on the floor for the Alliance quest Knowledge in the Deeps."),
 3: ("갈래 번개·얼음 회오리·감속. 탱커 뒤에 흩어져 서세요.", "Forked Lightning, Frost Nova, Slow. Spread out behind the tank."),
 4: ("안에서 만나는 은빛경비병. 대화하면 '타엘리드 찾기'가 끝나고 '검은심연의 음모'를 받습니다(양 진영).",
     "Argent Guard inside. Talk to finish his search quest and get Blackfathom Villainy (both factions)."),
 5: ("그물로 발을 묶습니다. 주변 멀록부터 정리하세요.", "Roots with Net; clear the murlocs around him first."),
 6: ("자리가 고정되지 않아 여러 곳 중 하나에 나타납니다(옅은 원이 후보). 번개 보호막과 번개 화살.",
     "Spawns at one of several spots (faint circles). Lightning Shield and Lightning Bolt."),
 7: ("물속에서 싸우는 상어. 수중 호흡 수단을 챙기고 숨 게이지를 보세요.", "Shark fought underwater. Bring water breathing, watch your breath."),
 8: ("호드 퀘스트로 불러내는 물의 정령. 그 퀘스트가 없으면 지나가세요.", "Water elemental summoned for a Horde quest; skip otherwise."),
 9: ("정신 분열과 수면. 수면 해제, 시전 차단.", "Mind Blast and Sleep. Dispel sleep, interrupt."),
 10: ("켈리스를 잡고 조각상 둘레 화로 넷을 차례로 처리하면 뒤쪽 문이 열립니다.", "After Kelris, work through the four braziers by the statue to open the back door."),
 11: ("독 구름을 깔고 체력이 낮으면 광폭해집니다. 구름에서 벗어나세요.", "Poison Cloud, frenzies at low health. Step out of clouds."),
},
"stockade": {
 1: ("감방 몇 곳 중 한 곳에 나타납니다(옅은 원이 후보). 쌍수 난타, 체력이 낮으면 분노.", "Spawns in one of several cells (faint circles). Thrash, enrages low."),
 2: ("감방 한 곳에 나오는 희귀 몹. 지나가도 됩니다.", "Rare in one of the cells. Skippable."),
 3: ("방어 태세에서 방패 밀쳐내기.", "Defensive Stance, Shield Slam."),
 4: ("연쇄 번개와 피의 욕망. 흩어져 서세요.", "Chain Lightning and Bloodlust; spread out."),
 5: ("연막탄으로 기절시키고 전투의 외침.", "Smoke Bomb stun and Battle Shout."),
 6: ("위협의 외침으로 공포. 공포 걸린 사람이 옆 무리를 끌 수 있으니 주변 감방을 먼저 비우세요.",
     "Intimidating Shout fears; feared players can pull cells, so clear around first."),
},
"gnomeregan": {
 1: ("폭발물전문가 에미에게 말을 걸면 에미가 입구를 폭파하는 동안 트로그가 몰려오고 끝에 그루비스가 나옵니다. 에미를 지키세요.",
     "Talk to Blastmaster Emi: troggs rush in while she seals the tunnels, then Grubbis comes. Keep Emi alive."),
 2: ("방사능 구역의 우두머리. 근처 방사능 몹에게서 얼라이언스 '유일한 치료법'의 폐기물을 얻습니다.",
     "Boss of the irradiated zone. Mobs here give the fallout for the Alliance quest The Only Cure is More Green Glow."),
 3: ("케르노비를 찾아 태엽장치 통로 출구까지 호위하세요('곤경에 빠진 케르노비'). 서 있는 자리는 여러 곳 중 하나.",
     "Find Kernobee and escort him to the Clockwerk Run exit (A Fine Mess). He stands at one of several spots."),
 4: ("정화 지역의 세척기. 꼬질꼬질한 반지를 넣어 닦습니다. 근처에 천공기록기 3005-B.",
     "Sparklematic in the Clean Zone: clean the Grime-Encrusted Ring here. Punchograph 3005-B is nearby."),
 5: ("전격·연쇄 벼락·100만 볼트. 흩어져 서세요. 작업장 열쇠를 떨구고, 방에 천공기록기 3005-C.",
     "Shock, Chain Bolt, Megavolt. Spread out. Drops the Workshop Key; Punchograph 3005-C in his room."),
 6: ("회전 강타·밟아 뭉개기·고철 압축으로 주변을 칩니다. 근접은 옆·뒤, 원거리는 멀리. 출격실에 3005-D.",
     "Arcing Smash, Trample, Crowd Pummel hit all around. Melee at sides/back, ranged far. Punchograph 3005-D in the bay."),
 7: ("희귀 몹. 화염구, 화염 보호막·냉기 갑옷, 불타는 하수인 소환. 지나가도 됩니다.", "Rare: Fireball, Fire Shield, Frost Armor, summons a servant. Skippable."),
 8: ("첩보원이 떨구는 꼬질꼬질한 반지로 같은 이름의 퀘스트가 시작됩니다. 여러 곳에 나옵니다.",
     "Agents drop the Grime-Encrusted Ring that starts its quest. Found in many places."),
 9: ("날려버리기로 탱커를 밀칩니다. 방 둘레 놈 얼굴 장치에서 폭탄 로봇이 나오니 장치를 누르거나 로봇을 먼저 처리.",
     "Knock Away on the tank. Bombs walk out of the gnome-face machines; press them or kill bombs first."),
 10: ("호드 '기술 전쟁'의 설계도가 든 금고. 비밀번호는 텔마플러그가 떨굽니다.", "Safe with the blueprints for the Horde quest Rig Wars; Thermaplugg drops the code."),
},
"razorfen-kraul": {
 1: ("번개 화살과 바위 정령 소환. 정령부터 잡으세요. 전사 퀘스트용 연소 약병을 떨굽니다.", "Lightning Bolt, summons an Earth Rumbler; kill it first. Drops the warrior quest vial."),
 2: ("전투의 외침, 멧돼지 정령 소환, 연쇄 치유. 치유를 끊으세요.", "Battle Shout, boar spirits, Chain Heal. Interrupt heals."),
 3: ("어둠의 화살과 정신 지배. 조종당한 사람은 묶어 두고 잘그바부터.", "Shadow Bolt and Dominate Mind. CC the controlled player, focus Jargba."),
 4: ("천둥벼락과 전투의 외침. 곁에 가시근위병이 붙어 있습니다.", "Thunderclap, Battle Shout; a Spearhide stands next to him."),
 5: ("램터스크 곁의 정예. 가시 오라와 소용돌이 탄막.", "Elite beside Ramtusk: Thorns Aura, Whirling Barrage."),
 6: ("희귀 몹. 바위 정령 소환, 속박의 토템, 번개 화살. 지나가도 됩니다.", "Rare: Earth Rumbler, Earthbind Totem, Lightning Bolt. Skippable."),
 7: ("맹렬한 돌진, 분노·격노. 탱커가 단단히 잡아 두세요.", "Rushing Charge, Enrage, Rampage. Tank must hold him firmly."),
 8: ("박쥐 동굴의 희귀 몹. 이 박쥐들이 호드 '조분석을 나에게!'의 조분석을 떨굽니다.", "Rare in the bat cave; the bats drop guano for the Horde quest."),
 9: ("갇혀 있는 윌릭스. 입구까지 호위하면 퀘스트 완료. 청엽수 줄기 자리도 이 근처에 많습니다.", "Willix is held here; escort him to the entrance. Many Blueleaf Tuber spots nearby."),
 10: ("헤랄라스의 주검. 얼라이언스 '꺼져가는 생명의 불씨'를 받습니다.", "Heralath's body gives the Alliance quest Mortality Wanes."),
 11: ("연쇄 벼락·마나 쐐기, 소생으로 회복. 흩어져 서고 소생을 해제하세요. 퀘스트용 메달·심장을 떨굽니다.",
     "Chain Bolt, Mana Spike, heals with Renew. Spread out and dispel Renew. Drops quest medallion/heart."),
},
"razorfen-downs": {
 1: ("징을 울리면 나타납니다. 거미줄로 묶고 저주를 걸며 근접 공격에 독이 묻어납니다.", "Ring the gong to summon it. Web Spray roots, curse, poisonous melee."),
 2: ("고약한 냄새와 부패의 손길. (지도 위치 미확인, Atlas 기준)", "Putrid Stench and Withered Touch. (Location unconfirmed; Atlas spot)"),
 3: ("화염구와 불꽃 회오리.", "Fireball and Fire Nova."),
 4: ("어둠의 화살·고통, 치유, 정신 지배. 치유를 끊으세요.", "Shadow Bolt, SW:Pain, heals and Dominate Mind. Interrupt heals."),
 5: ("질병 구름을 두르고 난타, 분노하면 더 세집니다.", "Disease Cloud, Thrash, hits harder when enraged."),
 6: ("얼음 화살·얼음 회오리·암네나르의 격노, 냉기 갑옷, 냉기 유령 소환.", "Frostbolt, Frost Nova, Amnennar's Wrath, Frost Armor, summons spectres."),
},
"scarlet-monastery-graveyard": {
 1: ("어둠의 권능: 고통과 제물. 해제 가능하면 해제하세요.", "Shadow Word: Pain and Immolate; dispel if you can."),
 2: ("비샤스 방에 갇혀 있습니다. 호드 '보렐의 복수'(결혼반지를 타렌 밀농장으로).", "Held in Vishas' room. Horde quest Vorrel's Revenge (ring to Tarren Mill)."),
 3: ("아즈쉬르·타락한 용사·무쇠해골 중 하나가 여러 자리 중 한 곳에 나옵니다(옅은 원이 후보).",
     "One of Azshir, the Fallen Champion or Ironspine spawns at one of several spots (faint circles)."),
 4: ("불의 쐐기·불꽃 회오리·화염 충격·어둠의 화살. 근접은 체력을 넉넉히. 묘지 끝 지하에 있습니다.",
     "Flame Spike, Fire Nova, Flame Shock, Shadow Bolt. Melee keep health up. In the crypt at the end."),
},
"scarlet-monastery-library": {
 1: ("사냥개와 함께 싸우며 피의 욕망·전투의 외침. 개부터 잡거나 광역으로.", "Fights with hounds, Bloodlust and Battle Shout. Dogs first or AoE."),
 2: ("서고 책장의 '티탄 신화'(얼라이언스 퀘스트).", "Mythology of the Titans on the shelves (Alliance quest)."),
 3: ("호드 '지혜의 시험'의 책 '언데드 위협의 기원'.", "The Beginnings of the Undead Threat for the Horde quest Test of Lore."),
 4: ("'타락의 개요'(호드 퀘스트).", "Compendium of the Fallen (Horde quest)."),
 5: ("'마력의 의식'(마법사 퀘스트).", "Rituals of Power (mage quest)."),
 6: ("침묵·신비한 폭발. 체력 절반에 거품을 두르고 주변을 변이시킨 뒤 폭발하니, 거품이 보이면 바로 멀리. 뒤쪽 금고에 붉은십자군 열쇠.",
     "Silence, Arcane Explosion. At half he bubbles, polymorphs nearby, then detonates: run when you see the bubble. Scarlet Key in the strongbox behind."),
},
"scarlet-monastery-armory": {
 1: ("회전베기·소용돌이, 체력이 낮으면 분노. 소용돌이 땐 근접도 물러서세요. 쓰러지면 수련생 무리가 몰려오니 모여서 광역으로.",
     "Cleave and Whirlwind, enrages low. Step back during Whirlwind. Trainees rush in on his death; group up and AoE."),
},
"scarlet-monastery-cathedral": {
 1: ("치유·보호막·마법 무효화로 버티고 피의 저주·공포·수면. 치유를 끊으세요.", "Heals, shields, dispels; Curse of Blood, Fear, Sleep. Interrupt heals."),
 2: ("예배당 제단 앞. 응보의 오라, 성전사의 일격, 심판의 망치, 위험하면 천상의 보호막. 쓰러뜨리면 화이트메인이 나옵니다.",
     "At the chapel altar. Retribution Aura, Crusader Strike, HoJ, Divine Shield. Killing him brings Whitemane."),
 3: ("성스러운 일격·치유·보호막. 체력 절반에 모두를 재우고 모그레인을 되살립니다. 그때를 위해 체력과 마나를 남겨 두세요.",
     "Holy Smite, heals, shields. At half she sleeps everyone and revives Mograine; save health and mana for it."),
},
"uldaman": {
 1: ("번개 화살과 연쇄 번개.", "Lightning Bolt and Chain Lightning."),
 2: ("밸로그(사격·일격)·에릭(돌진)·올라프(방패 밀쳐내기·완벽 방어) 셋과 함께 싸웁니다.", "Baelog (Shoot, Strike), Eric (Rushing Charge) and Olaf (Shield Slam, 100% Block) together."),
 3: ("날려버리기·전투 발구르기·회전 강타. (지도 위치 미확인, Atlas 기준)", "Knock Away, War Stomp, Arcing Smash. (Location unconfirmed; Atlas spot)"),
 4: ("주문 반사와 흑요석 파편 소환.", "Spell Reflection and Obsidian Shards."),
 5: ("모래 폭풍을 일으킵니다.", "Summons Sand Storms."),
 6: ("화염 채찍·화염 충격·불꽃 회오리, 화염계 증폭.", "Flame Lash, Flame Shock, Fire Nova, Amplify Flames."),
 7: ("번개 화살·연쇄 벼락·축소, 피의 욕망.", "Lightning Bolt, Chain Bolt, Shrink, Bloodlust."),
 8: ("제단을 쓰면 깨어납니다. 지진, 방 둘레 석상들을 깨워 싸움에 끌어들입니다.", "Wakes when you use the altar. Ground Tremor; awakens the statues around the room."),
},
"hall-of-thanes": {
 1: ("입구 다음 큰 방(앤빌마의 휴식처). 망령이 가득하니 앞만 비우든 방을 다 치우든 편한 대로. 정신 분열은 차단, 탱커 공속을 늦추는 저주를 겁니다.",
     "Big hall past the entrance, full of ghosts; clear in front or the whole room. Interrupt Mind Blast; curse slows the tank's attacks."),
 2: ("휴식처에서 동쪽 깊은 곳. 소환사와 함께 오니 소환사부터. 연소(차단 불가, 12초 화염)와 즉시 화염 폭발. 비근접은 떨어져 서세요.",
     "Deep to the east. Comes with a Summoner: kill it first. Combust (12s, can't kick) and instant Fire Nova; non-melee stand back."),
 3: ("마그마투스 방에서 서쪽 끝 큰 본당. 복도를 순찰하니 구석으로 끌어오세요. 넉백이 있으니 벽을 등지고.",
     "West to the great hall of thrones. Patrols his corridor; pull into a cleared corner. Knock Away, so back to a wall."),
 4: ("약탈골렘 다음 북쪽 '왕가의 성물 보관소'. 옆 약탈자와 작은 돌 골렘부터. 출혈과 8초 광역 공포가 있으니 방을 미리 비우세요.",
     "North to the Reliquary of Kings. Clear looters and the small golems first. Rend and an 8s AoE fear; empty the room beforehand."),
},
"excavation-site": {
 1: ("잃어버린 늪의 악어 우두머리(정예 야수). 기술 정보는 아직 없습니다.", "Crocolisk boss of the Lost Marsh (elite beast). Abilities not known yet."),
 2: ("추적자의 숲 랩터 우두머리. 이 숲 랩터들이 '덤불 랩터 가죽'을 떨굽니다.", "Raptor boss of Stalker's Thicket; raptors here drop Thicket Raptor Hides."),
 3: ("늪지 괴물 정령. 선택 우두머리일 수 있습니다. 얼라이언스 퀘스트용 뿌리핵을 떨굽니다.", "Bog beast; may be optional. Drops the root core for an Alliance quest."),
 4: ("수호자의 터의 돌 골렘, 마지막 우두머리. 퀘스트를 시작하는 티탄의 유물을 떨굽니다.", "Stone golem at the Site of the Guardian, last boss. Drops the Titan Relic quest item."),
},
"ruins-of-lordaeron": {
 1: ("입구를 나와 바로 왼쪽(북쪽) 벽돌 길의 NPC. 얼라이언스 '흉측한 괴물들'을 주고받습니다(남작의 머리).",
     "Just left (north) of the entrance on the brick path. Alliance quest Abominable Creatures (the Baron's head)."),
 2: ("동쪽 거미 구역 넓은 방. 쫄 셋을 달고 긴 복도를 순찰하니, 자리를 비운 사이 남은 무리를 치우세요. 탱커에게 흡혈 독. 호드 '새로운 역병'의 균주.",
     "Big room in the east spider area. Patrols the hallway with three adds; clear while she's away. Leech Poison on the tank. Horde quest item."),
 3: ("게임 안 이름은 '남작'. 거대한 누더기골렘이라 한 방이 아주 셉니다. 탱커 기절·띄우기·전방 베기. 부탱커를 정해 두고 딜러는 어그로 조절.",
     "Shown as The Baron in game. Huge abomination: Knockout stuns the tank, knock-up, cleave. Assign an off-tank; DPS watch threat."),
 4: ("이벤트로 나오는 숨은 우두머리. 문간에 들어서면 시작해 적이 세 차례 몰려오고 네 번째에 내려옵니다. 얼음 회오리, 생명력 흡수(차단 가능).",
     "Hidden event boss: step into the doorway, three waves, then he descends. Frost Nova and Life Drain (interruptible)."),
 5: ("서쪽 시장 거리 북서쪽 안개 구역을 도는 거대한 트롤 언데드. 해골·구울이 많아 광역이 좋습니다. 대마법 보호막, 넉백. 벽을 등지고.",
     "Giant undead troll roaming the foggy NW of Market Street. Lots of trash: AoE helps. Anti-magic shell and knockback; tank on a wall."),
 6: ("연못 동쪽으로 내려가 울타리 친 보라색 룬 위의 마지막 우두머리. 룬에서 끌어내세요. 진짜 위험은 불기둥: 차단 순서를 정하고 놓치면 바로 피하세요.",
     "Final boss on a fenced purple rune, south past the pools. Pull him off the rune. Flamestrike is the danger: set kicks, dodge misses."),
 7: ("숨은 우두머리. 둥근 탑 옆 벽난로에 불을 붙이면 다섯 차례 공세 뒤 나타납니다. 근접이 매우 세고 흡혈 독. 자원이 넉넉할 때 하세요.",
     "Hidden boss: light the fireplace by the round tower; five waves, then him. Hard melee and Leech Poison. Do it with resources to spare."),
 8: ("희귀 정예라 매번 나오지 않습니다. 다른 우두머리를 다 잡은 뒤 서쪽에 나올 수 있고 호드만 공격 가능하다는 정보가 있습니다.",
     "Rare elite, not always up. Reportedly may appear in the west after all bosses; only attackable by the Horde."),
},
"dalaran": {
 1: ("블리즈컨 시연 기준. 하수도 지나 지하 의식의 원. 무장 해제, 해골 소환. 호드 퀘스트 대상.", "BlizzCon demo: Ritual Circle in the Underbelly. Disarms, raises skeletons. Horde quest target."),
 2: ("시연 기준. 둥근 테라스의 거품 안에서 끌려 나옵니다. 비전 화살과 광선 공격.", "Demo: pulled from a bubble on the Round Terrace. Arcane Bolt and a beam."),
 3: ("시연 기준. 지옥 기운 스민 나무정령들 사이. 기술 정보 없음.", "Demo: among fel-suffused treants. Abilities unknown."),
 4: ("시연 기준. 마법 거래소에서 성난 마법서들과 함께. 25미터 광역 오작동.", "Demo: Magus Commerce Exchange with Angry Tomes. 25-yard Malfunction."),
 5: ("자리와 기술 정보 없음.", "Location and abilities unknown."),
 6: ("게임 안 이름 Arcanic Enigma. 얼라이언스 퀘스트 대상.", "Named Arcanic Enigma in game. Alliance quest target."),
 7: ("희귀 정예, 매번 나오지 않을 수 있습니다.", "Rare elite; may not always appear."),
 8: ("정예 일반 몹에 가깝다는 정보도 있습니다.", "Possibly closer to elite trash."),
 9: ("시연 기준 마지막 우두머리, 보랏빛 성채. 튀는 마나 공격과 파티 전체 변이. 전멸하면 방이 처음으로.", "Demo final boss in the Violet Citadel. Bounding Mana and group polymorph; room resets on wipe."),
},
}

NOTES = {
"ragefire-chasm": [("화염 피해가 계속 들어오니 물약·붕대를 넉넉히.", "Constant fire damage: bring potions and bandages."),
                   ("저주·독 해제가 있으면 두 우두머리가 쉬워집니다.", "Decurse and poison cures make two bosses easy.")],
"wailing-caverns": [("송곳니의 드루이드는 치유의 손길을 씁니다. 차단을 나눠 맡으세요.", "Fanglords heal: assign interrupts."),
                    ("층이 겹친 동굴입니다. 함부로 뛰어내리면 돌아오기 어렵습니다.", "Layered caves: jumping down can split the group."),
                    ("랩터는 체력이 줄면 주변을 부릅니다. 주변을 비우고 잡으세요.", "Raptors call help at low health; clear around first.")],
"deadmines": [("달빛시내 마을 가는 길에 데피아즈단 정예가 돌아다닙니다. 입구 앞에서 모이세요.", "Defias elites roam Moonbrook; meet at the entrance."),
              ("밴클리프가 떨구는 '부치지 않은 편지'를 챙기세요.", "Loot The Unsent Letter from VanCleef.")],
"shadowfang-keep": [("레실고어 다음 감옥에서 진영 NPC를 풀어야 안뜰 문이 열립니다.", "Free your faction's prisoner after Rethilgore to open the courtyard."),
                    ("지도는 여러 층을 한 장에 겹쳐 그린 것입니다.", "The map flattens several floors into one.")],
"blackfathom-deeps": [("수중 구간이 있습니다. 수중 호흡 수단을 챙기세요.", "Underwater sections: bring water breathing."),
                      ("지도는 세 장입니다. 창 아래 페이지 버튼으로 넘겨 보세요.", "Three map pages; switch with the page buttons.")],
"stockade": [("죄수가 감방마다 뭉쳐 있습니다. 문 앞에서 끌어내 복도에서 잡으세요.", "Prisoners clump in cells; pull them into the corridor."),
             ("얼라이언스는 스톰윈드 안이라 오가기 쉽습니다.", "Easy access for the Alliance inside Stormwind.")],
"gnomeregan": [("천공 카드 퀘스트: 흰 카드를 3005 기계에 차례로 넣습니다. A는 밖, B·C·D는 안.", "Punch card quest: feed the card into the 3005 machines (A outside, B/C/D inside)."),
               ("기계화 문지기 6000의 작업장 열쇠로 다음부터 뒷문으로 들어올 수 있습니다.", "Electrocutioner's Workshop Key opens the back entrance next time.")],
"razorfen-kraul": [("아겜과 차를가는 스스로 치유합니다. 차단을 준비하세요.", "Aggem and Charlga heal themselves; have interrupts."),
                   ("청엽수 줄기 퀘스트는 들어오기 전에 톱니항에서 상자·지휘봉·설명서를 챙기세요.", "Blueleaf Tubers: grab crate, stick and manual in Ratchet first.")],
"razorfen-downs": [("25레벨부터 입장할 수 있습니다.", "Entry from level 25.")],
"scarlet-monastery-graveyard": [("수도원 날개 넷은 입구와 인스턴스가 따로입니다. 보통 묘지→도서관→무기고→대성당 순.", "Four wings, separate entrances. Usual order: GY, Library, Armory, Cathedral.")],
"scarlet-monastery-library": [("서고에서 줍는 책: 티탄 신화(얼), 타락의 개요(호), 언데드 위협의 기원(호), 마력의 의식(마법사).", "Books here: Titans (A), Compendium (H), Undead Threat (H), Rituals (mage).")],
"scarlet-monastery-armory": [("헤로드가 소용돌이를 돌 때 원거리와 힐러는 떨어져 서세요.", "Ranged and healers stay away during Herod's Whirlwind.")],
"scarlet-monastery-cathedral": [("대성당 들어가기 전, 정원 무리를 문 앞으로 끌어 따로 잡으세요. 예배당 몹을 같이 끌면 모그레인이 합세합니다.", "Pull courtyard packs to the door; pulling chapel mobs brings Mograine.")],
"uldaman": [("30레벨부터 입장할 수 있습니다.", "Entry from level 30.")],
"hall-of-thanes": [("내려가는 길 아래가 용암입니다. 길에서 벗어나지 마세요.", "Lava below the descending path; stay on it."),
                   ("마그마투스 구간은 화염 저항 물약이 도움이 됩니다.", "Fire resistance potions help for Magmatus."),
                   ("이 던전은 지형 그림 없이 상대 위치만 표시합니다.", "No terrain art for this dungeon; markers show relative positions only.")],
"excavation-site": [("만남의 돌은 저습지 53.4, 65.3입니다.", "Meeting stone: Wetlands 53.4, 65.3."),
                    ("추적자의 숲에 정예 랩터가 많습니다.", "Many elite raptors in Stalker's Thicket."),
                    ("이 던전은 지형 그림 없이 상대 위치만 표시합니다.", "No terrain art; relative positions only.")],
"ruins-of-lordaeron": [("쇠퇴송곳니가 쫄을 데리고 순찰합니다. 경로를 보고 시작하세요.", "Witherfang patrols with adds; watch her path."),
                       ("'로데론의 문장'은 자리가 고정되지 않습니다. 건물 바닥을 살펴보세요.", "The Crest of Lordaeron has no fixed spot; check building floors."),
                       ("이 던전은 지형 그림 없이 상대 위치만 표시합니다.", "No terrain art; relative positions only.")],
"dalaran": [("블리즈컨 시연을 기준으로 한 정보라 실제와 다를 수 있습니다.", "Based on the BlizzCon demo; may differ."),
            ("지도 자료가 없어 목록만 제공합니다.", "No map data yet; list only.")],
}
